export type NodeDetail = {
  title: string; category: string; color: string;
  description: string;
  responsibilities: string[];
  tech: string[];
  apiRoutes?: { method: string; path: string; desc: string }[];
  classes?: { name: string; fields?: string[]; methods?: string[] }[];
  notes?: string;
};

export const DETAILS: Record<string, NodeDetail> = {

  client: {
    title: "Client Layer", category: "Frontend", color: "#e50914",
    description: "Every device Netflix runs on — Smart TVs, iOS, Android, Web (React), Roku, PlayStation, Xbox. Each platform has a native SDK. The client authenticates, fetches metadata via API, then streams video DIRECTLY from the nearest OCA — API servers never proxy video bytes. Adaptive bitrate algorithm (BOLA) switches quality chunk-by-chunk based on buffer health and bandwidth.",
    responsibilities: [
      "Bootstrap auth flow → get JWT + refresh token",
      "Fetch homepage, catalog, search results from API",
      "Call Playback Service → receive signed DASH/HLS manifest",
      "Stream video chunks directly from nearest OCA",
      "BOLA adaptive bitrate switching mid-stream",
      "DRM decryption inside Trusted Execution Environment (TEE)",
      "Heartbeat POST every 30s → update resume position",
      "Offline download with DRM-encrypted local files",
      "Report QoE events: buffer stalls, bitrate changes, errors",
    ],
    tech: ["React 18 (Web)", "Swift UIKit/SwiftUI (iOS/tvOS)", "Kotlin (Android)", "DASH (MPD manifests)", "HLS (m3u8 manifests)", "Widevine CDM", "FairPlay Streaming", "PlayReady"],
    classes: [
      { name: "NetflixApp", methods: ["launch() → void", "authenticate(credentials) → Session", "loadHomePage(profileId) → HomePage", "startPlayback(titleId, episodeId) → PlaybackSession"] },
      { name: "PlaybackEngine", fields: ["currentBitrate: Int", "bufferHealthMs: Long", "sessionId: UUID", "manifestUrl: String"], methods: ["loadManifest(url) → Manifest", "selectQuality(bandwidth, buffer) → QualityLevel  // BOLA", "downloadChunk(url, range) → Chunk", "decryptChunk(chunk, drmKey) → RawFrame", "sendHeartbeat(positionMs, bitrate)"] },
      { name: "DRMManager", methods: ["acquireLicense(keyId, licenseUrl) → License", "renewLicense(licenseId) → License", "revokeLicense(licenseId)", "isLicenseValid(licenseId) → Boolean"] },
      { name: "OfflineManager", methods: ["downloadEpisode(episodeId, quality) → Download", "getDownloads() → List<Download>", "deleteDownload(downloadId)", "isExpired(downloadId) → Boolean  // 48h after first play"] },
      { name: "QoEReporter", methods: ["reportPlayStart(sessionId)", "reportBufferStall(sessionId, durationMs)", "reportBitrateChange(sessionId, fromKbps, toKbps)", "reportError(sessionId, errorCode, message)"] },
    ],
    notes: "95%+ of all Netflix traffic (video bytes) goes Client → OCA directly. API servers only handle metadata, auth, and manifests.",
  },

  cdn: {
    title: "Open Connect (CDN)", category: "CDN", color: "#e50914",
    description: "Netflix's own CDN. ~17,000 Open Connect Appliances (OCAs) co-located inside ISP data centers globally — free colocation for ISPs in exchange for better peering. 3-tier hierarchy: Embed OCA (inside ISP) → Exchange OCA (at IXPs) → Netflix Origin (S3). During off-peak hours, a fill algorithm proactively pushes the predicted-popular content to OCAs. ~100 Tbps peak bandwidth served.",
    responsibilities: [
      "Serve all video chunks to clients",
      "Proactive nightly cache fill based on popularity prediction",
      "3-tier hierarchy: Embed → Exchange → S3 Origin fallback",
      "BGP Anycast routing for nearest OCA resolution",
      "Cache miss → fetch from tier above, cache locally",
      "Health reporting to Steering Service every 10s",
      "Serve signed URLs only — reject unsigned requests",
    ],
    tech: ["Custom OCA hardware (100TB NVMe + HDD)", "FreeBSD", "nginx (custom)", "BGP Anycast", "HTTPS with signed URL tokens"],
    classes: [
      { name: "OCA", fields: ["ocaId: String", "ispId: String", "tier: Enum(EMBED|EXCHANGE|ORIGIN)", "capacityTB: Int", "cachedTitles: Set<VideoId>", "healthScore: Float"], methods: ["serveChunk(videoId, range, token) → Chunk", "isCached(videoId) → Boolean", "fetchFromUpstream(videoId) → void", "reportHealth() → HealthReport"] },
      { name: "CacheFillScheduler", methods: ["predictPopularContent(region, date) → List<VideoId>", "scheduleFill(ocaId, videoIds) → FillJob", "executeFill(fillJobId) → void", "getFillStatus(fillJobId) → FillStatus"] },
    ],
  },

  elb: {
    title: "AWS Elastic Load Balancer", category: "Infrastructure", color: "#f97316",
    description: "Netflix runs on AWS (after migrating from own DCs in 2016). ELB is the first hop for all API traffic — distributes across Zuul2 instances in multiple AZs. Route53 health checks detect region failures and shift traffic within ~30s. Netflix runs active-active across 3 AWS regions: us-east-1, us-west-2, eu-west-1.",
    responsibilities: [
      "Layer 7 load balancing across Zuul2 fleet",
      "Health checks on Zuul instances",
      "SSL/TLS termination at edge",
      "Cross-AZ traffic distribution",
      "Route53 DNS failover between regions (30s RTO)",
      "DDoS protection via AWS Shield",
    ],
    tech: ["AWS ALB (Application Load Balancer)", "AWS Route53 (latency-based routing)", "AWS Shield (DDoS)", "ACM (SSL certificates)"],
    classes: [
      { name: "RegionRouter", methods: ["resolveRegion(clientIP) → Region", "isRegionHealthy(region) → Boolean", "failover(fromRegion, toRegion) → void"] },
    ],
    notes: "During Chaos Kong tests, Netflix takes down an entire AWS region and verifies Route53 shifts traffic automatically within 30s.",
  },

  eureka: {
    title: "Eureka + Ribbon (Service Mesh)", category: "Infrastructure", color: "#6366f1",
    description: "Eureka is Netflix's open-sourced service registry — each microservice registers itself on startup and sends heartbeats every 30s. Ribbon is the client-side load balancer — every service uses Ribbon to discover and call other services without a central proxy. Combines with Archaius for dynamic config and Hystrix for circuit breaking.",
    responsibilities: [
      "Service registration on startup",
      "Heartbeat-based health tracking (30s intervals)",
      "Service discovery for all inter-service calls",
      "Client-side load balancing via Ribbon (round-robin / weighted)",
      "Zone-aware routing — prefer same AZ",
      "Self-preservation mode — don't evict if >85% of services miss heartbeat",
    ],
    tech: ["Eureka Server (Spring Cloud)", "Ribbon (client-side LB)", "Archaius (dynamic config)", "Hystrix (circuit breaker)"],
    classes: [
      { name: "EurekaClient", fields: ["serviceId: String", "instanceId: String", "ipAddr: String", "port: Int", "status: UP|DOWN|STARTING|OUT_OF_SERVICE"], methods: ["register() → void", "sendHeartbeat() → void  // every 30s", "deregister() → void", "getInstances(serviceId) → List<InstanceInfo>"] },
      { name: "RibbonLoadBalancer", methods: ["chooseServer(serviceId) → Server  // round-robin / zone-aware", "markServerDown(server)", "getAllServers(serviceId) → List<Server>"] },
      { name: "Archaius", methods: ["getProperty(key) → String", "setProperty(key, value) → void  // hot-reload without restart", "getDynamicIntProperty(key, default) → DynamicIntProperty"] },
    ],
  },

  zuul: {
    title: "Zuul2 API Gateway", category: "Gateway", color: "#f59e0b",
    description: "Single entry point for all client API traffic. Zuul2 (async, non-blocking via Netty) replaced Zuul1 (thread-per-request). Every inbound request passes through a filter chain: pre-filters (auth, rate limit), routing filters (pick microservice), post-filters (logging, response decoration), error filters. Handles >1M requests/second.",
    responsibilities: [
      "JWT validation on every request",
      "Rate limiting: per-user (100 req/s), per-device, per-IP",
      "Request routing to 1000+ microservices via Eureka",
      "A/B test traffic splitting (route % to experiment variant)",
      "SSL termination + HTTP/2 support",
      "Correlation ID injection (tracing)",
      "GZIP compression of responses",
      "Request/response logging to Kafka",
    ],
    tech: ["Zuul2 (Netty async)", "Ribbon (client-side LB)", "Eureka (discovery)", "JWT (RS256)", "Caffeine cache (rate limit counters)"],
    apiRoutes: [
      { method: "ALL", path: "/*", desc: "All routes proxied through Zuul — no direct service exposure" },
    ],
    classes: [
      { name: "ZuulFilter (abstract)", fields: ["filterType: pre|route|post|error", "filterOrder: Int", "shouldFilter: Boolean"], methods: ["shouldFilter() → Boolean", "run() → Object", "filterType() → String", "filterOrder() → Int"] },
      { name: "AuthFilter extends ZuulFilter", methods: ["validateJWT(token) → Claims", "extractUserId(claims) → UUID", "extractDeviceId(claims) → UUID", "run() → void  // throws 401 if invalid"] },
      { name: "RateLimitFilter extends ZuulFilter", methods: ["getUserBucket(userId) → RateBucket", "checkLimit(bucket, limit) → Boolean  // throws 429 if exceeded", "incrementCounter(userId, endpoint)"] },
      { name: "RoutingFilter extends ZuulFilter", methods: ["resolveService(path) → ServiceId", "getInstance(serviceId) → InstanceInfo  // via Ribbon", "forwardRequest(instance, request) → Response"] },
      { name: "LoggingFilter extends ZuulFilter", methods: ["injectCorrelationId(request) → String", "logRequest(correlationId, userId, path, ms)", "publishToKafka(accessLog)"] },
    ],
  },

  auth: {
    title: "Auth Service", category: "Microservice", color: "#8b5cf6",
    description: "Issues and validates JWTs, manages OAuth2 social login, device registry, and session lifecycle. Access tokens: 15-minute TTL (RS256 signed). Refresh tokens: 30-day TTL stored in Redis. Supports account linking (Facebook, Google, Apple Sign-In). Device fingerprinting detects account sharing.",
    responsibilities: [
      "Login with email/password (bcrypt hash comparison)",
      "OAuth2: Google, Facebook, Apple Sign-In",
      "Issue JWT access token (15 min) + refresh token (30 days)",
      "Token refresh without re-login",
      "Revoke all sessions (account compromise)",
      "Device registration and fingerprinting",
      "Password reset flow (email token, 1h TTL)",
      "MFA support (TOTP authenticator apps)",
    ],
    tech: ["Redis (sessions + refresh tokens)", "MySQL (device registry, OAuth accounts)", "JWT RS256", "bcrypt (cost 12)", "TOTP (RFC 6238)"],
    apiRoutes: [
      { method: "POST", path: "/auth/login", desc: "email + password → access_token, refresh_token, deviceId" },
      { method: "POST", path: "/auth/logout", desc: "Invalidate session, delete refresh token from Redis" },
      { method: "POST", path: "/auth/refresh", desc: "refresh_token → new access_token (rotate refresh token)" },
      { method: "DELETE", path: "/auth/sessions", desc: "Revoke ALL sessions for userId (account compromise)" },
      { method: "POST", path: "/auth/oauth/:provider", desc: "OAuth2 callback → link account or create new user" },
      { method: "POST", path: "/auth/password/reset/request", desc: "Send reset email with signed token (1h TTL)" },
      { method: "POST", path: "/auth/password/reset/confirm", desc: "token + newPassword → update hash, revoke sessions" },
      { method: "GET",  path: "/auth/devices", desc: "List all registered devices for userId" },
      { method: "DELETE", path: "/auth/devices/:deviceId", desc: "Remove trusted device" },
    ],
    classes: [
      { name: "AuthService", methods: ["login(email, password, deviceInfo) → AuthToken", "logout(accessToken) → void", "refreshToken(refreshToken) → AuthToken", "validateToken(token) → Claims", "revokeAllSessions(userId) → void", "registerDevice(userId, fingerprint) → Device"] },
      { name: "AuthToken", fields: ["accessToken: JWT  // 15 min, RS256", "refreshToken: UUID  // 30 days, stored in Redis", "tokenType: 'Bearer'", "expiresIn: 900", "deviceId: UUID", "profileId: UUID"] },
      { name: "Device", fields: ["deviceId: UUID", "userId: UUID", "deviceType: TV|MOBILE|WEB|TABLET|GAME_CONSOLE", "fingerprint: String", "lastSeen: Timestamp", "trusted: Boolean", "name: String  // 'John's iPhone'"] },
      { name: "PasswordResetService", methods: ["requestReset(email) → void  // send email with signed token", "validateResetToken(token) → UserId", "confirmReset(token, newPassword) → void"] },
      { name: "OAuthService", methods: ["handleCallback(provider, code) → AuthToken", "linkAccount(userId, provider, oauthId) → void", "unlinkAccount(userId, provider) → void"] },
      { name: "SessionStore (Redis)", methods: ["storeRefreshToken(userId, deviceId, token, ttl)", "getRefreshToken(token) → Session", "deleteRefreshToken(token)", "deleteAllUserSessions(userId)"] },
    ],
  },

  user: {
    title: "User Service", category: "Microservice", color: "#3b82f6",
    description: "Manages user accounts, up to 5 profiles per account, preferences, watch history, and parental controls. Strict ACID consistency needed — changes to email/plan tie to billing. Profile-level isolation: each profile has its own watch history, recommendations, and maturity rating.",
    responsibilities: [
      "User account CRUD (email, password hash, plan, country)",
      "Profile management — up to 5 profiles per account",
      "Per-profile maturity rating and PIN lock",
      "Language + subtitle preferences per profile",
      "Watch history read/write per profile",
      "Continue watching list",
      "My List (watchlist) management",
    ],
    tech: ["MySQL sharded by userId", "EVCache (profile cache, TTL 5 min)", "Kafka (user-activity events)"],
    apiRoutes: [
      { method: "GET",    path: "/users/me", desc: "Get current user account details" },
      { method: "PATCH",  path: "/users/me", desc: "Update email, country, communication prefs" },
      { method: "GET",    path: "/users/me/profiles", desc: "List all profiles for account" },
      { method: "POST",   path: "/users/me/profiles", desc: "Create new profile (max 5)" },
      { method: "PATCH",  path: "/users/me/profiles/:profileId", desc: "Update profile name, avatar, language, maturity" },
      { method: "DELETE", path: "/users/me/profiles/:profileId", desc: "Delete profile (irreversible, removes history)" },
      { method: "GET",    path: "/users/me/profiles/:profileId/history", desc: "Paginated watch history" },
      { method: "DELETE", path: "/users/me/profiles/:profileId/history/:titleId", desc: "Remove title from history" },
      { method: "GET",    path: "/users/me/list", desc: "My List (watchlist) for active profile" },
      { method: "PUT",    path: "/users/me/list/:titleId", desc: "Add title to My List" },
      { method: "DELETE", path: "/users/me/list/:titleId", desc: "Remove from My List" },
    ],
    classes: [
      { name: "User", fields: ["userId: UUID", "email: String", "passwordHash: String  // bcrypt", "plan: BASIC|STANDARD|PREMIUM", "countryCode: String", "createdAt: Timestamp", "emailVerified: Boolean"] },
      { name: "Profile", fields: ["profileId: UUID", "userId: UUID", "name: String", "avatarUrl: String", "maturityRating: LITTLE_KIDS|OLDER_KIDS|TEEN|ALL", "pinEnabled: Boolean", "pinHash: String", "language: String", "audioLanguage: String", "subtitleLanguage: String"] },
      { name: "WatchHistoryService", methods: ["recordWatch(profileId, titleId, episodeId, positionMs, completedAt)", "getHistory(profileId, page, limit) → List<WatchEvent>", "getContinueWatching(profileId) → List<WatchEvent>", "removeFromHistory(profileId, titleId)"] },
      { name: "WatchEvent", fields: ["watchId: UUID", "profileId: UUID", "titleId: UUID", "episodeId: UUID", "positionMs: Long", "durationMs: Long", "watchedAt: Timestamp", "completed: Boolean"] },
      { name: "MyListService", methods: ["addTitle(profileId, titleId) → void", "removeTitle(profileId, titleId) → void", "getList(profileId) → List<TitleId>", "isInList(profileId, titleId) → Boolean"] },
    ],
  },

  catalog: {
    title: "Catalog Service", category: "Microservice", color: "#10b981",
    description: "Central repository of all Netflix content metadata — 36,000+ titles, localized for 190+ countries. Handles movies, series, seasons, episodes, trailers, supplemental content. Heavily read-cached via EVCache. Writes are rare (new content ingestion) but reads are on every page load.",
    responsibilities: [
      "Title CRUD with versioning",
      "Season and episode hierarchy for series",
      "Localized metadata — titles, synopses, dubbing per locale",
      "Regional availability — which titles per country",
      "Maturity ratings per region (different standards globally)",
      "Cast, crew, genre, mood, content tags",
      "Trailer and supplemental video asset links",
    ],
    tech: ["Cassandra (partition by titleId, high read throughput)", "EVCache (hot titles, 5 min TTL)", "Elasticsearch (search index, faceted filtering)", "S3 (thumbnails, artwork assets)"],
    apiRoutes: [
      { method: "GET",  path: "/catalog/titles/:titleId", desc: "Full title metadata including cast, genres, availability" },
      { method: "GET",  path: "/catalog/titles/:titleId/seasons", desc: "All seasons for a series" },
      { method: "GET",  path: "/catalog/titles/:titleId/seasons/:seasonId/episodes", desc: "Episodes in a season" },
      { method: "GET",  path: "/catalog/genres", desc: "List all genres for region" },
      { method: "GET",  path: "/catalog/genres/:genreId/titles", desc: "Paginated titles in genre" },
      { method: "GET",  path: "/catalog/trending?region=US", desc: "Trending titles for region (cached)" },
      { method: "GET",  path: "/catalog/new-releases?region=US", desc: "New releases this week" },
      { method: "GET",  path: "/catalog/titles/:titleId/similar", desc: "Similar titles (from recommendation service)" },
    ],
    classes: [
      { name: "Title", fields: ["titleId: UUID", "type: MOVIE|SERIES|SHORT|DOCUMENTARY|STANDUP", "originalTitle: String", "localizedTitles: Map<Locale, String>", "localizedSynopses: Map<Locale, String>", "genres: List<Genre>", "cast: List<CastMember>", "directors: List<Person>", "releaseYear: Int", "durationMs: Long  // for MOVIE", "availableCountries: Set<CountryCode>", "maturityRatings: Map<CountryCode, String>", "averageRating: Float", "thumbnailUrls: Map<ArtworkType, String>"] },
      { name: "Season", fields: ["seasonId: UUID", "titleId: UUID", "seasonNumber: Int", "releaseYear: Int", "episodeCount: Int", "synopsis: String"] },
      { name: "Episode", fields: ["episodeId: UUID", "seasonId: UUID", "episodeNumber: Int", "title: String", "synopsis: String", "durationMs: Long", "videoId: UUID", "thumbnailUrl: String", "releaseDate: Date"] },
      { name: "CastMember", fields: ["personId: UUID", "name: String", "role: String", "characterName: String", "orderIndex: Int"] },
    ],
  },

  search: {
    title: "Search Service", category: "Microservice", color: "#14b8a6",
    description: "Full-text search over titles, cast, synopsis, genres, and transcripts (from subtitle files). Autocomplete uses a Redis sorted set of top queries. Results are re-ranked by a personalization layer using the user's watch history. Filtered by region availability and maturity rating.",
    responsibilities: [
      "Full-text search (BM25 + semantic vector search)",
      "Autocomplete with top-N suggestions from Redis",
      "Faceted filtering: genre, year, type, maturity",
      "Results re-ranked by user personalization model",
      "Filter by regional availability + maturity rating",
      "Index new/updated titles from Kafka content events",
      "Person search (actor/director → their titles)",
    ],
    tech: ["Elasticsearch (BM25 + dense vector kNN)", "Redis (autocomplete sorted set)", "Kafka (index update consumer)"],
    apiRoutes: [
      { method: "GET", path: "/search?q=&profileId=&page=&limit=", desc: "Full search with personalized re-ranking" },
      { method: "GET", path: "/search/autocomplete?prefix=", desc: "Top suggestions for prefix (Redis zset)" },
      { method: "GET", path: "/search/person/:personId", desc: "All titles featuring this person" },
    ],
    classes: [
      { name: "SearchService", methods: ["search(query, profileId, filters, page) → SearchResult", "autocomplete(prefix, limit) → List<Suggestion>", "searchByPerson(personId) → List<Title>", "reindex(titleId) → void  // triggered by Kafka"] },
      { name: "SearchResult", fields: ["query: String", "results: List<RankedTitle>", "totalCount: Int", "facets: SearchFacets", "personalizationApplied: Boolean", "durationMs: Int"] },
      { name: "SearchFacets", fields: ["genres: Map<String, Int>", "types: Map<ContentType, Int>", "years: Map<Int, Int>"] },
      { name: "SearchIndexer", methods: ["indexTitle(title: Title) → void", "deleteTitle(titleId) → void", "buildDocument(title) → EsDocument"] },
    ],
  },

  playback: {
    title: "Playback Service", category: "Microservice", color: "#ef4444",
    description: "Most critical service — target latency < 300ms. Checks entitlement, enforces concurrent stream limits, selects the best OCA via Steering Service, generates a signed DASH/HLS manifest URL, and returns a DRM license token. The client then streams video DIRECTLY from the OCA — this service is completely out of the video path after manifest delivery.",
    responsibilities: [
      "Check billing entitlement (active subscription?)",
      "Acquire stream slot from Concurrency Service",
      "Call Steering Service → get best OCA endpoint",
      "Generate signed manifest URL (HMAC-SHA256, 6h TTL)",
      "Generate DRM license token (Widevine/FairPlay/PlayReady)",
      "Write initial resume position to Cassandra",
      "Publish PLAY event to Kafka topic: playback-events",
      "Handle heartbeat events → update resume position",
      "Release stream slot on END event",
    ],
    tech: ["Cassandra (resume position, written every 30s)", "Redis (active stream slots via Concurrency)", "Kafka (playback-events topic)", "HMAC-SHA256 (signed manifest URLs)"],
    apiRoutes: [
      { method: "POST", path: "/playback/start", desc: "{ titleId, episodeId, deviceInfo } → PlaybackManifest" },
      { method: "POST", path: "/playback/:sessionId/heartbeat", desc: "{ positionMs, bitrate, bufferMs } → 200 OK" },
      { method: "POST", path: "/playback/:sessionId/end", desc: "{ positionMs, reason } → release slot" },
      { method: "GET",  path: "/playback/resume/:episodeId", desc: "Get last resume position for profile" },
      { method: "POST", path: "/playback/:sessionId/event", desc: "Report QoE event (buffer, quality change)" },
    ],
    classes: [
      { name: "PlaybackService", methods: ["startPlayback(userId, titleId, episodeId, deviceInfo) → PlaybackManifest", "heartbeat(sessionId, event) → void", "endPlayback(sessionId, finalPositionMs) → void", "getResumePosition(profileId, episodeId) → Long"] },
      { name: "PlaybackManifest", fields: ["sessionId: UUID", "manifestUrl: String  // signed, 6h TTL", "licenseUrl: String  // DRM license endpoint", "heartbeatIntervalMs: 30000", "encodingProfiles: List<EncodingProfile>", "expiresAt: Timestamp"] },
      { name: "PlaybackEvent", fields: ["sessionId: UUID", "eventType: PLAY|PAUSE|SEEK|BUFFER_START|BUFFER_END|QUALITY_CHANGE|HEARTBEAT|END|ERROR", "positionMs: Long", "bitrateKbps: Int", "bufferHealthMs: Long", "errorCode: String", "timestamp: Timestamp"] },
      { name: "EncodingProfile", fields: ["profileId: String  // e.g. 'hd-h264-5800k'", "codec: H264|H265|AV1|VP9", "resolution: 480p|720p|1080p|4K", "bitrateKbps: Int", "hdr: NONE|HDR10|DOLBY_VISION", "audioCodec: AAC|AC3|ATMOS"] },
    ],
    notes: "startPlayback() target: < 300ms p99. After manifest returned, API servers are completely out of the hot path — all video bytes flow Client ↔ OCA.",
  },

  steering: {
    title: "Steering Service", category: "Microservice", color: "#f97316",
    description: "Selects the optimal OCA (Open Connect Appliance) for each playback request. Considers: client ISP, client location, which OCAs have the requested title cached, OCA health scores, current load, and network conditions measured via periodic probes. Returns a ranked list of OCA endpoints.",
    responsibilities: [
      "Maintain real-time OCA health map (updated every 10s)",
      "Determine which OCAs have a given videoId cached",
      "Rank OCAs by: ISP match > latency > load > capacity",
      "Fall back to Exchange OCA if Embed miss",
      "Fall back to S3 origin if full cache miss",
      "Network probe analysis (RTT measurements)",
    ],
    tech: ["In-memory OCA state map", "Consistent hashing for OCA selection", "BGP table analysis for ISP matching"],
    apiRoutes: [
      { method: "POST", path: "/steering/resolve", desc: "{ clientIP, videoId, deviceType } → List<OCAEndpoint> ranked" },
      { method: "GET",  path: "/steering/health", desc: "OCA health map snapshot" },
    ],
    classes: [
      { name: "SteeringService", methods: ["resolveOCA(clientIP, videoId, deviceType) → List<OCAEndpoint>", "getOCAHealth(ocaId) → HealthScore", "updateOCAHealth(ocaId, report) → void", "getOCAsWithTitle(videoId) → List<OCAId>"] },
      { name: "OCAEndpoint", fields: ["ocaId: String", "url: String", "tier: EMBED|EXCHANGE|ORIGIN", "ispId: String", "latencyMs: Int", "loadPercent: Float", "hasTitle: Boolean"] },
      { name: "HealthScore", fields: ["ocaId: String", "available: Boolean", "loadPercent: Float", "avgLatencyMs: Float", "errorRate: Float", "lastUpdated: Timestamp"] },
    ],
  },

  drm: {
    title: "DRM License Service", category: "Security", color: "#dc2626",
    description: "Issues DRM licenses for Widevine (Android/Chrome), FairPlay (Apple), and PlayReady (Windows/Xbox). A license contains the decryption key for the requested content — issued only to verified, entitled users with a valid playback session. Keys are never persisted on the client unencrypted; they live only in the device's Trusted Execution Environment (TEE).",
    responsibilities: [
      "Validate playback session token before issuing license",
      "Check entitlement — is user allowed to watch this title?",
      "Issue Widevine license (Chrome, Android, Smart TVs)",
      "Issue FairPlay Streaming license (iOS, tvOS, macOS, Safari)",
      "Issue PlayReady license (Windows, Xbox, Edge)",
      "Enforce rental/download license expiry (48h play window)",
      "Key rotation on suspected compromise",
    ],
    tech: ["Widevine Modular DRM (Google)", "FairPlay Streaming (Apple)", "PlayReady (Microsoft)", "AES-128 CBC / AES-128 CTR content encryption", "HSM (Hardware Security Module) for key storage"],
    apiRoutes: [
      { method: "POST", path: "/drm/widevine/license", desc: "sessionToken + Widevine license request → encrypted license" },
      { method: "POST", path: "/drm/fairplay/license", desc: "sessionToken + FairPlay SPC blob → CKC response" },
      { method: "POST", path: "/drm/playready/license", desc: "sessionToken + PlayReady challenge → license XML" },
    ],
    classes: [
      { name: "DRMLicenseService", methods: ["issueWidevineLicense(sessionToken, licenseRequest) → WidevineLicense", "issueFairPlayLicense(sessionToken, spcBlob) → CKCResponse", "issuePlayReadyLicense(sessionToken, challenge) → PlayReadyLicense", "revokeLicense(sessionId) → void", "isEntitled(userId, titleId) → Boolean"] },
      { name: "ContentKey", fields: ["keyId: UUID", "keyValue: Bytes  // stored in HSM, never in DB plaintext", "titleId: UUID", "algorithm: AES128_CBC|AES128_CTR", "rotatedAt: Timestamp"] },
    ],
    notes: "Decryption keys only ever exist in the device TEE (ARM TrustZone / Intel SGX). If the device is jailbroken, Widevine L1 license is refused; L3 (software-only) issued instead with lower quality cap.",
  },

  billing: {
    title: "Billing Service", category: "Microservice", color: "#ec4899",
    description: "Manages subscriptions, payment processing, and plan entitlement. Uses MySQL for ACID guarantees — money requires strict consistency. Payment cards are never stored raw — tokenized via Stripe/Braintree. Failed payments trigger a retry schedule (3 attempts over 30 days) before subscription suspension. Publishes entitlement events to Kafka consumed by Playback Service.",
    responsibilities: [
      "Subscription lifecycle: create, cancel, pause, resume, upgrade/downgrade",
      "Payment processing via Stripe (tokenized cards)",
      "Failed payment retry schedule (day 1, 7, 14, 30)",
      "Proration on mid-cycle plan changes",
      "Invoice generation and PDF export",
      "Publish entitlement events to Kafka",
      "Gift card and promo code redemption",
      "Tax calculation per country",
    ],
    tech: ["MySQL (ACID, sharded by userId)", "Stripe API (card tokenization + charges)", "Kafka (billing-events topic)", "PDF generation (invoices)"],
    apiRoutes: [
      { method: "GET",    path: "/billing/subscription", desc: "Get current subscription details" },
      { method: "POST",   path: "/billing/subscription", desc: "Create subscription { plan, paymentMethodId }" },
      { method: "PATCH",  path: "/billing/subscription", desc: "Change plan (proration applied)" },
      { method: "DELETE", path: "/billing/subscription", desc: "Cancel at end of billing period" },
      { method: "POST",   path: "/billing/payment-methods", desc: "Add payment method (Stripe token → store tokenId)" },
      { method: "DELETE", path: "/billing/payment-methods/:id", desc: "Remove payment method" },
      { method: "GET",    path: "/billing/invoices", desc: "Paginated invoice history" },
      { method: "GET",    path: "/billing/invoices/:id/pdf", desc: "Download invoice PDF" },
      { method: "POST",   path: "/billing/promo", desc: "Redeem promo/gift code" },
    ],
    classes: [
      { name: "Subscription", fields: ["subscriptionId: UUID", "userId: UUID", "plan: BASIC|STANDARD|PREMIUM", "status: ACTIVE|CANCELLED|PAUSED|PAST_DUE|TRIALING", "currentPeriodStart: Date", "currentPeriodEnd: Date", "cancelAtPeriodEnd: Boolean", "paymentMethodId: UUID"] },
      { name: "Plan", fields: ["BASIC: { price: $6.99, streams: 1, resolution: 480p, downloads: false }", "STANDARD: { price: $15.49, streams: 2, resolution: 1080p, downloads: 2_devices }", "PREMIUM: { price: $22.99, streams: 4, resolution: 4K+HDR, downloads: 6_devices }"] },
      { name: "PaymentMethod", fields: ["paymentMethodId: UUID", "userId: UUID", "stripeTokenId: String  // never store raw PAN", "type: CREDIT|DEBIT|PAYPAL|GIFT_CARD", "lastFour: String", "brand: String", "expiryMonth: Int", "expiryYear: Int", "isDefault: Boolean"] },
      { name: "Invoice", fields: ["invoiceId: UUID", "userId: UUID", "amount: Money", "currency: String", "status: PAID|OPEN|VOID", "items: List<InvoiceItem>", "createdAt: Date", "paidAt: Date"] },
      { name: "PaymentRetrySchedule", methods: ["scheduleRetry(userId, attempt) → void  // day 1, 7, 14, 30", "executeRetry(userId) → PaymentResult", "suspendOnFailure(userId) → void  // after 4 failures"] },
    ],
  },

  recommendation: {
    title: "Recommendation Service", category: "ML/AI", color: "#a855f7",
    description: "80% of watched content comes from recommendations. Uses matrix factorization + two-tower neural networks for collaborative filtering. Contextual bandits determine homepage row ordering. Even thumbnail artwork is personalized per user via a separate multi-armed bandit model. Offline Spark jobs retrain models nightly; online layer does lightweight re-ranking at request time.",
    responsibilities: [
      "Personalized homepage row generation per profile",
      "Two-tower NN: user embedding × item embedding → similarity score",
      "Matrix factorization (ALS) for collaborative filtering",
      "Contextual bandit for row ordering (exploration vs exploitation)",
      "Artwork personalization — different thumbnail per user segment",
      "Nightly Spark/EMR model retraining from Kafka events",
      "Pre-compute recommendations → Cassandra (read at <5ms)",
      "Online re-ranking with fresh context (device, time of day)",
    ],
    tech: ["TensorFlow / PyTorch (model training)", "Apache Spark on EMR (offline training)", "Cassandra (pre-computed recs)", "EVCache (homepage cache, 5 min TTL)", "Kafka (user-activity consumer for retraining)"],
    apiRoutes: [
      { method: "GET", path: "/recommendations/homepage/:profileId?device=", desc: "Full personalized homepage" },
      { method: "GET", path: "/recommendations/similar/:titleId?profileId=", desc: "Titles similar to given title" },
      { method: "GET", path: "/recommendations/row/:profileId?rowType=", desc: "Single row: CONTINUE_WATCHING|TOP_10|TRENDING|BECAUSE_YOU_WATCHED" },
    ],
    classes: [
      { name: "RecommendationService", methods: ["getHomepage(profileId, deviceType, timestamp) → HomePage", "getSimilarTitles(titleId, profileId, limit) → List<RankedTitle>", "getRow(profileId, rowType, limit) → HomeRow", "rankCandidates(profileId, candidates) → List<RankedTitle>"] },
      { name: "HomePage", fields: ["profileId: UUID", "rows: List<HomeRow>", "generatedAt: Timestamp", "experimentVariant: String"] },
      { name: "HomeRow", fields: ["rowId: String", "displayTitle: String  // 'Because you watched Stranger Things'", "algorithm: TWO_TOWER|TRENDING|CONTINUE_WATCHING|TOP10|NEW_RELEASES", "titles: List<RankedTitle>", "rank: Int  // row position, bandit-determined"] },
      { name: "RankedTitle", fields: ["title: Title", "score: Float", "artworkVariant: String  // A/B tested per user", "reason: String"] },
      { name: "TwoTowerModel", methods: ["getUserEmbedding(profileId) → Float[]  // 256-dim", "getItemEmbedding(titleId) → Float[]", "score(userEmb, itemEmb) → Float  // dot product", "getTopK(profileId, k) → List<TitleId>"] },
      { name: "ArtworkBandit", methods: ["selectArtwork(profileId, titleId) → ArtworkVariant", "recordImpression(profileId, titleId, variant)", "recordClick(profileId, titleId, variant)", "updateModel() → void  // UCB algorithm"] },
    ],
    notes: "Artwork personalization: a romance viewer sees a couple, an action viewer sees an explosion — same title, different thumbnail. Drives ~20% uplift in click-through rate.",
  },

  notification: {
    title: "Notification Service", category: "Microservice", color: "#06b6d4",
    description: "Async event-driven notifications across email, push, and SMS. Consumes events from Kafka — billing failures, new episode releases, content recommendations, account security alerts. Templates are localized per user language. Deduplication prevents spam (same notification not sent twice in 24h).",
    responsibilities: [
      "Push notifications via FCM (Android) and APNs (iOS)",
      "Transactional email via AWS SES",
      "SMS via Twilio (payment failures, security alerts)",
      "Template rendering with localization",
      "Deduplication (24h window per user+type)",
      "Retry with exponential backoff on delivery failure",
      "Opt-out/preference management per channel",
      "Scheduled notifications (new episode at release time)",
    ],
    tech: ["Firebase FCM (Android push)", "Apple APNs (iOS push)", "AWS SES (email)", "Twilio (SMS)", "Kafka (event consumer)", "Redis (dedup + scheduling)"],
    apiRoutes: [
      { method: "GET",    path: "/notifications/preferences", desc: "Get user notification preferences per channel" },
      { method: "PATCH",  path: "/notifications/preferences", desc: "Update opt-in/out per channel and type" },
      { method: "GET",    path: "/notifications/history", desc: "Last 50 notifications sent to user" },
    ],
    classes: [
      { name: "NotificationService", methods: ["sendPush(userId, template, data) → void", "sendEmail(userId, template, data) → void", "sendSMS(userId, message) → void", "scheduleNotification(userId, type, triggerAt, data) → void", "cancelScheduled(notificationId) → void"] },
      { name: "NotificationEvent (Kafka)", fields: ["eventId: UUID", "userId: UUID", "type: NEW_EPISODE|PAYMENT_FAILED|WELCOME|SECURITY_ALERT|RECOMMENDATION|ACCOUNT_SHARING_DETECTED", "channel: EMAIL|PUSH|SMS", "payload: Map<String,Object>", "scheduledAt: Timestamp"] },
      { name: "TemplateEngine", methods: ["render(templateId, locale, data) → String", "getTemplate(templateId, locale) → Template"] },
      { name: "DeduplicationService", methods: ["isDuplicate(userId, type) → Boolean  // 24h window", "markSent(userId, type, channel)"] },
    ],
  },

  abtest: {
    title: "A/B Testing (XP Platform)", category: "Platform", color: "#84cc16",
    description: "Netflix runs hundreds of simultaneous experiments — every UI change, recommendation tweak, encoding parameter, and thumbnail variant is A/B tested before rollout. Deterministic bucket assignment (hash of userId + experimentId) ensures users always see the same variant. Kayenta auto-analyzes canary deployments and rolls back if metrics degrade.",
    responsibilities: [
      "Deterministic variant assignment (hash-based, no DB lookup on hot path)",
      "Traffic allocation: control % vs treatment %",
      "Exposure logging → analytics pipeline",
      "Statistical significance calculation",
      "Kayenta: automated canary analysis on deploys",
      "Auto-rollback if error rate / latency degrades",
      "Multi-variate experiments (A/B/C/D)",
      "Feature flag management (gradual rollout %)",
    ],
    tech: ["EVCache (variant assignment cache)", "Kafka (exposure events)", "Druid (real-time experiment metrics)", "Kayenta (canary analysis — open-sourced by Netflix)"],
    apiRoutes: [
      { method: "GET",  path: "/xp/variant/:experimentId?userId=", desc: "Get variant for user in experiment (deterministic)" },
      { method: "POST", path: "/xp/exposure", desc: "Log that user was exposed to variant" },
      { method: "GET",  path: "/xp/experiments/:experimentId/results", desc: "Statistical results (lift, p-value, CI)" },
      { method: "GET",  path: "/xp/flags/:flagId?userId=", desc: "Feature flag value for user" },
    ],
    classes: [
      { name: "ExperimentService", methods: ["getVariant(userId, experimentId) → Variant  // hash(userId+expId) % 100", "logExposure(userId, experimentId, variant) → void", "getResults(experimentId) → ExperimentResults"] },
      { name: "Experiment", fields: ["experimentId: UUID", "name: String", "variants: List<Variant>  // control + treatments", "trafficAllocation: Map<Variant, Float>", "metric: String  // e.g. play_rate, completion_rate", "minSampleSize: Int", "startDate: Date", "status: RUNNING|STOPPED|WINNER_DECLARED"] },
      { name: "FeatureFlagService", methods: ["isEnabled(flagId, userId) → Boolean", "getValue(flagId, userId) → String", "setRollout(flagId, percent) → void"] },
      { name: "KayentaCanaryAnalyzer", methods: ["startAnalysis(canaryConfig) → AnalysisId", "getScore(analysisId) → CanaryScore  // 0-100", "shouldRollback(analysisId) → Boolean  // score < threshold"] },
    ],
  },

  concurrency: {
    title: "Concurrency Control", category: "Microservice", color: "#f43f5e",
    description: "Enforces simultaneous stream limits per plan (Basic: 1, Standard: 2, Premium: 4). Uses Redis atomic INCR/DECR with TTL. The heartbeat from the client (every 30s) refreshes the TTL — if the client crashes without explicitly calling END, the slot auto-frees when TTL expires. Also powers Netflix's 2023 account-sharing enforcement.",
    responsibilities: [
      "Acquire stream slot on playback start (atomic Redis INCR)",
      "Reject with HTTP 429 if over plan limit",
      "Release slot on explicit END event (atomic Redis DECR)",
      "TTL-based auto-release on client crash (36s TTL, refreshed every 30s)",
      "Track active streams: userId → List<StreamInfo>",
      "Account sharing detection: flag concurrent streams from different households",
      "Device-level concurrent stream tracking",
    ],
    tech: ["Redis (atomic INCR/DECR with TTL, Lua scripts for atomicity)", "Lua scripting (check-then-set atomically)"],
    apiRoutes: [
      { method: "POST",   path: "/concurrency/acquire", desc: "{ userId, deviceId, sessionId } → StreamToken or 429" },
      { method: "DELETE", path: "/concurrency/release/:sessionId", desc: "Release stream slot immediately" },
      { method: "POST",   path: "/concurrency/heartbeat/:sessionId", desc: "Refresh TTL for active session" },
      { method: "GET",    path: "/concurrency/active/:userId", desc: "List active streams for user" },
    ],
    classes: [
      { name: "ConcurrencyService", methods: ["acquireStream(userId, deviceId, sessionId) → StreamToken  // HTTP 429 if over limit", "releaseStream(sessionId) → void", "heartbeat(sessionId) → void  // refresh TTL to 36s", "getActiveStreams(userId) → List<StreamInfo>", "getPlanLimit(userId) → Int"] },
      { name: "StreamToken", fields: ["sessionId: UUID", "userId: UUID", "deviceId: UUID", "acquiredAt: Timestamp", "expiresAt: Timestamp  // now + 36s, refreshed by heartbeat"] },
      { name: "StreamInfo", fields: ["sessionId: UUID", "deviceType: String", "location: String  // IP-derived", "titleId: UUID", "startedAt: Timestamp"] },
    ],
    notes: "Lua script atomicity: KEYS[1]=stream_count:{userId}, KEYS[2]=stream_set:{userId}. Check count < limit, INCR and SADD in single atomic operation — prevents race condition where two simultaneous streams both pass the check.",
  },

  download: {
    title: "Download Service", category: "Microservice", color: "#7c3aed",
    description: "Manages offline downloads for Standard (2 devices) and Premium (6 devices) plans. Downloads are DRM-encrypted locally — only playable in the Netflix app. Licenses expire 48h after first play or 30 days from download, whichever comes first. License renewal happens automatically when the app comes online.",
    responsibilities: [
      "Check download entitlement (plan allows downloads?)",
      "Provide download URLs with device-bound DRM token",
      "Track download count per device (per-plan limits)",
      "Expiry management: 30d download window, 48h play window",
      "License renewal when device comes back online",
      "Delete expired downloads to free storage",
      "Available quality: Standard=1080p, Premium=4K",
    ],
    tech: ["Cassandra (download metadata per user)", "DRM Service (device-bound license)", "S3/OCA (encrypted video files)"],
    apiRoutes: [
      { method: "GET",    path: "/downloads", desc: "List active downloads for profile" },
      { method: "POST",   path: "/downloads", desc: "{ episodeId, quality, deviceId } → DownloadToken" },
      { method: "DELETE", path: "/downloads/:downloadId", desc: "Delete download + revoke DRM license" },
      { method: "POST",   path: "/downloads/:downloadId/renew", desc: "Renew DRM license (device online)" },
      { method: "GET",    path: "/downloads/:downloadId/status", desc: "Check download expiry status" },
    ],
    classes: [
      { name: "DownloadService", methods: ["initiateDownload(profileId, episodeId, quality, deviceId) → Download", "getDownloads(profileId) → List<Download>", "deleteDownload(downloadId) → void", "renewLicense(downloadId) → Download", "cleanupExpired() → Int  // background job"] },
      { name: "Download", fields: ["downloadId: UUID", "profileId: UUID", "episodeId: UUID", "deviceId: UUID", "quality: Resolution", "status: QUEUED|DOWNLOADING|READY|EXPIRED|DELETED", "downloadedAt: Timestamp", "expiresAt: Timestamp  // 30d from download", "playWindowExpiresAt: Timestamp  // 48h from first play", "fileSizeBytes: Long", "drmLicenseId: UUID"] },
    ],
  },

  encoding: {
    title: "Encoding Pipeline", category: "Infrastructure", color: "#ea580c",
    description: "Raw studio masters (4K ProRes, 8K RED RAW) become 1,200+ encoded versions per title — every combination of resolution × codec × HDR × audio. Netflix's key innovation: Per-Title Encoding. Each title's scene complexity is analyzed; bitrate per chunk is assigned based on actual visual complexity, not a fixed ladder. Saves ~20% bandwidth at same quality.",
    responsibilities: [
      "Ingest raw studio masters from partner portals",
      "Scene complexity analysis for per-title encoding",
      "Encode: H.264 (compatibility), H.265/HEVC (efficiency), AV1 (next-gen), VP9",
      "Resolution ladder: 240p → 360p → 480p → 720p → 1080p → 4K",
      "HDR: SDR + HDR10 + Dolby Vision + HLG",
      "Audio: Stereo + 5.1 Surround + Dolby Atmos",
      "Subtitle processing: TTML/WebVTT per language",
      "DRM encryption before storage (AES-128)",
      "Push encoded chunks to OCAs via content-publish-events Kafka topic",
    ],
    tech: ["AWS EC2 GPU/CPU fleets (massive parallelism)", "FFmpeg (custom Netflix fork)", "S3 (encoded output)", "Kafka (job state machine + content-publish-events)"],
    classes: [
      { name: "EncodingPipeline", methods: ["ingestMaster(titleId, sourceS3Key, metadata) → EncodingJob", "analyzeComplexity(jobId) → ComplexityReport", "buildBitrateLadder(complexityReport) → List<TargetProfile>", "encodeParallel(jobId, profiles) → List<EncodedAsset>", "encryptAssets(assets, contentKey) → List<EncryptedAsset>", "publishToOCAs(titleId, assets) → void"] },
      { name: "EncodingJob", fields: ["jobId: UUID", "titleId: UUID", "sourceS3Key: String", "status: QUEUED|ANALYZING|ENCODING|ENCRYPTING|PUBLISHING|DONE|FAILED", "profiles: List<TargetProfile>", "createdAt: Timestamp", "completedAt: Timestamp", "durationMs: Long"] },
      { name: "TargetProfile", fields: ["codec: H264|H265|AV1|VP9", "resolution: 240p|360p|480p|720p|1080p|4K", "targetBitrateKbps: Int  // per-title, not fixed", "hdr: NONE|HDR10|DOLBY_VISION|HLG", "audioCodec: AAC|AC3|EAC3|ATMOS", "outputS3Key: String"] },
      { name: "SceneAnalyzer", methods: ["analyzeSpatialComplexity(frame) → Float  // DCT-based", "analyzeTemporalComplexity(frames) → Float  // motion vectors", "detectSceneBoundaries(video) → List<Long>  // timestamps", "assignBitratePerScene(complexities) → Map<SceneId, Int>"] },
    ],
    notes: "Per-title encoding: a simple animated film gets ~1,000 kbps for 1080p; a dark action film gets ~4,000 kbps for the same resolution and quality. Same VMAF score, wildly different file size.",
  },

  kafka: {
    title: "Apache Kafka", category: "Messaging", color: "#f59e0b",
    description: "The nervous system of Netflix — ~1 trillion events per day. Every meaningful action in every microservice produces a Kafka event. 7-day retention in Kafka; archived to S3 as Parquet (Iceberg tables) via Kafka Connect. Powers real-time analytics (Flink), async service communication, and ML model retraining triggers.",
    responsibilities: [
      "Decouple producers from consumers — services don't call each other for events",
      "playback-events: heartbeats, end, QoE metrics",
      "billing-events: subscription changes, payment success/fail → entitlement updates",
      "content-publish-events: new encoded content → OCA cache fill",
      "user-activity: watch, search, thumbs → recommendation retraining",
      "encoding-job-events: job state machine",
      "notification-events: trigger email/push/SMS",
      "access-log-events: Zuul → analytics",
    ],
    tech: ["Apache Kafka (AWS MSK managed)", "Schema Registry + Avro (schema enforcement)", "Kafka Connect → S3 Parquet sink", "Kafka Streams (lightweight in-process processing)"],
    classes: [
      { name: "KafkaProducer<K,V>", methods: ["send(topic, key, value) → Future<RecordMetadata>", "sendSync(topic, key, value) → RecordMetadata", "flush() → void", "close() → void"] },
      { name: "KafkaConsumer<K,V>", methods: ["subscribe(topics) → void", "poll(durationMs) → ConsumerRecords<K,V>", "commitSync(offsets) → void", "pause(partitions) → void", "seek(partition, offset) → void"] },
      { name: "PlaybackEventSchema (Avro)", fields: ["sessionId: string", "userId: string", "titleId: string", "eventType: enum{PLAY,PAUSE,SEEK,BUFFER,HEARTBEAT,END,ERROR}", "positionMs: long", "bitrateKbps: int", "bufferHealthMs: long", "timestamp: long"] },
      { name: "BillingEventSchema (Avro)", fields: ["eventId: string", "userId: string", "eventType: enum{SUBSCRIBED,CANCELLED,PAYMENT_SUCCESS,PAYMENT_FAILED,PLAN_CHANGED}", "plan: string", "amount: double", "timestamp: long"] },
    ],
    notes: "Key topics: playback-events · billing-events · content-publish-events · user-activity · encoding-job-events · notification-events · access-log-events. All topics use Avro + Schema Registry to prevent schema drift.",
  },

  cassandra: {
    title: "Apache Cassandra", category: "Database", color: "#06b6d4",
    description: "World's largest Cassandra deployment — ~10,000 nodes across multiple data centers. Used for all high-write, high-read workloads that can tolerate eventual consistency: watch history, resume positions, pre-computed recommendations, playback session metadata. Partition keys are carefully designed — no cross-partition queries allowed.",
    responsibilities: [
      "Watch history: partition (profileId, year), clustering by watchedAt DESC",
      "Resume position: partition (profileId, episodeId) — written every 30s per active stream",
      "Pre-computed recommendations: partition by profileId",
      "Playback session metadata",
      "Title metadata (read replica, partition by titleId)",
      "Multi-DC replication (us-east-1, us-west-2, eu-west-1)",
    ],
    tech: ["Apache Cassandra 4.x", "CQL (Cassandra Query Language)", "Multi-DC replication (NetworkTopologyStrategy)", "Tunable consistency: QUORUM for critical reads, ONE for high-volume writes"],
    classes: [
      { name: "watch_history table", fields: ["PRIMARY KEY ((profile_id, year), watched_at) WITH CLUSTERING ORDER BY (watched_at DESC)", "profile_id: UUID", "year: INT", "watched_at: TIMESTAMP", "title_id: UUID", "episode_id: UUID", "position_ms: BIGINT", "duration_ms: BIGINT", "completed: BOOLEAN"] },
      { name: "resume_position table", fields: ["PRIMARY KEY (profile_id, episode_id)", "profile_id: UUID", "episode_id: UUID", "position_ms: BIGINT", "updated_at: TIMESTAMP", "session_id: UUID"] },
      { name: "recommendations table", fields: ["PRIMARY KEY (profile_id, row_type, rank)", "profile_id: UUID", "row_type: TEXT", "rank: INT", "title_id: UUID", "score: FLOAT", "computed_at: TIMESTAMP"] },
      { name: "CassandraDAO", methods: ["executeQuery(cql, params) → ResultSet", "executeAsync(cql, params) → CompletableFuture<ResultSet>", "executeBatch(statements) → void", "prepareStatement(cql) → PreparedStatement"] },
    ],
    notes: "Rule: every query must hit a single partition. No ALLOW FILTERING. No joins. Design tables around query patterns, not normalization.",
  },

  mysql: {
    title: "MySQL (RDS)", category: "Database", color: "#3b82f6",
    description: "Used for all data requiring ACID guarantees: user accounts, billing/subscriptions, device registry, OAuth accounts, invoices. Sharded by userId. Netflix uses RDS Multi-AZ with read replicas. Strict consistency is non-negotiable here — money and auth cannot tolerate stale reads.",
    responsibilities: [
      "User accounts and credentials",
      "Billing subscriptions and invoices",
      "Payment methods (tokenized, no raw PAN)",
      "Device registry and OAuth account links",
      "Password reset tokens",
      "Audit log for billing/auth events",
    ],
    tech: ["MySQL 8.0 on AWS RDS", "Multi-AZ (synchronous replication)", "Read replicas for reporting queries", "ProxySQL for connection pooling", "Sharding by userId (consistent hashing)"],
    classes: [
      { name: "users table", fields: ["user_id BINARY(16) PRIMARY KEY", "email VARCHAR(255) UNIQUE", "password_hash VARCHAR(60)  // bcrypt", "plan ENUM('BASIC','STANDARD','PREMIUM')", "country_code CHAR(2)", "created_at DATETIME", "email_verified TINYINT(1)"] },
      { name: "subscriptions table", fields: ["subscription_id BINARY(16) PRIMARY KEY", "user_id BINARY(16) FK→users", "plan ENUM", "status ENUM('ACTIVE','CANCELLED','PAST_DUE','PAUSED')", "current_period_start DATE", "current_period_end DATE", "cancel_at_period_end TINYINT(1)", "stripe_subscription_id VARCHAR(255)"] },
      { name: "payment_methods table", fields: ["payment_method_id BINARY(16) PRIMARY KEY", "user_id BINARY(16) FK→users", "stripe_token_id VARCHAR(255)  // no raw PAN", "last_four CHAR(4)", "brand VARCHAR(20)", "expiry_month TINYINT", "expiry_year SMALLINT", "is_default TINYINT(1)"] },
    ],
    notes: "Writes go to primary RDS instance (Multi-AZ, synchronous standby). Reporting queries use read replicas. Never use Cassandra for billing — eventual consistency + money = disaster.",
  },

  redis: {
    title: "Redis", category: "Database", color: "#ef4444",
    description: "Used for all sub-millisecond, TTL-based state: auth refresh tokens, concurrent stream slots (with atomic Lua scripts), search autocomplete sorted sets, rate limit counters, and notification deduplication. Separate from EVCache (Memcached-based) — Redis is for data that needs TTL precision, Lua atomicity, or sorted set operations.",
    responsibilities: [
      "Auth refresh tokens: key=token, value=session JSON, TTL=30d",
      "Stream slots: key=streams:{userId}, value=count, TTL=36s (refreshed by heartbeat)",
      "Rate limit counters: key=ratelimit:{userId}:{endpoint}:{window}, TTL=1min",
      "Search autocomplete: ZADD top_queries, ZRANGEBYLEX for prefix search",
      "Notification deduplication: key=notif_sent:{userId}:{type}, TTL=24h",
      "Password reset tokens: key=reset:{token}, value=userId, TTL=1h",
      "Scheduled notification queue: sorted set by triggerAt timestamp",
    ],
    tech: ["Redis 7 Cluster", "Redis Sentinel (HA)", "Lua scripting (atomic check-and-set)", "Redis Streams (lightweight event log)"],
    classes: [
      { name: "RedisSessionStore", methods: ["set(token, session, ttlSeconds) → void", "get(token) → Session", "delete(token) → void", "deletePattern(userId + ':*') → Int  // revoke all sessions"] },
      { name: "StreamSlotStore (Lua)", methods: ["acquireSlot(userId, limit, sessionId, ttl) → Boolean  // atomic check+INCR+SADD", "releaseSlot(userId, sessionId) → void  // atomic DECR+SREM", "refreshTTL(userId, sessionId, ttl) → void", "getActiveCount(userId) → Int"] },
      { name: "RateLimiter", methods: ["checkLimit(userId, endpoint, limitPerMin) → Boolean  // sliding window", "incrementCounter(userId, endpoint) → Int", "getRemainingQuota(userId, endpoint) → Int"] },
    ],
    notes: "Stream slot acquire is a Lua script for atomicity: check count < limit, INCR, SADD in a single atomic Redis operation — prevents TOCTOU race conditions.",
  },

  evcache: {
    title: "EVCache", category: "Cache", color: "#10b981",
    description: "Netflix's Memcached wrapper (open-sourced). Replicates cache writes to all AZs simultaneously — reads served from local AZ at sub-millisecond latency. Handles ~30M requests/second at peak. An AZ failure is transparent to callers because other AZs have the data. Used for hot title metadata, homepage recommendations, session tokens, and A/B variant assignments.",
    responsibilities: [
      "Cache hot title metadata (TTL: 5 min)",
      "Cache pre-computed homepage recommendations (TTL: 5 min)",
      "Cache session tokens / JWT validation results (TTL: match token TTL)",
      "A/B experiment variant assignments (TTL: 24h)",
      "Rate limit counters fallback (if Redis overloaded)",
      "Multi-AZ replication on every write",
    ],
    tech: ["Memcached (underlying)", "EVCache client (Netflix OSS)", "Multi-AZ write replication", "Zonal read preference", "~30M req/s peak"],
    classes: [
      { name: "EVCacheClient", methods: ["set(key, value, ttlSeconds) → void  // replicates to all AZs", "get(key) → Optional<Value>  // reads from local AZ", "delete(key) → void  // deletes from all AZs", "getOrLoad(key, loader, ttl) → Value  // cache-aside pattern", "getBulk(keys) → Map<String,Value>"] },
      { name: "CacheKey conventions", fields: ["title:{titleId} → Title JSON, TTL 5m", "homepage:{profileId}:{deviceType} → HomePage JSON, TTL 5m", "xp:variant:{userId}:{experimentId} → Variant, TTL 24h", "session:{tokenHash} → Session JSON, TTL matches token"] },
    ],
  },

  analytics: {
    title: "Data Pipeline & Analytics", category: "Data", color: "#34d399",
    description: "Kafka events feed two paths: Flink for real-time metrics (< 1s latency) and Kafka Connect → S3 Parquet/Iceberg for batch analytics. Spark on EMR retrains recommendation models nightly. Druid powers sub-second interactive queries on billions of rows. Netflix uses this to measure every A/B test, monitor encoding quality, and track engagement.",
    responsibilities: [
      "Flink: real-time A/B test metrics, anomaly detection, live dashboards",
      "Kafka Connect: archive all topics to S3 as Parquet (Iceberg format)",
      "Spark/EMR: nightly recommendation model retraining",
      "Spark/EMR: encoding quality analysis (VMAF scores)",
      "Presto/Athena: ad-hoc SQL on Iceberg tables",
      "Druid: sub-second interactive analytics for ops teams",
    ],
    tech: ["Apache Flink (real-time, sub-second)", "Apache Spark on EMR (batch)", "Apache Iceberg on S3 (table format: ACID, time travel)", "Apache Druid (interactive analytics)", "Presto / AWS Athena (SQL on S3)", "Kafka Connect (S3 sink connector)"],
    classes: [
      { name: "FlinkPlaybackJob", methods: ["processEvent(PlaybackEvent) → void", "aggregateBufferRate(window: 1min) → BufferMetric", "detectAnomalies(metrics) → List<Anomaly>", "emitToPrometheus(metric) → void"] },
      { name: "SparkRecommendationTrainer", methods: ["loadUserActivity(date) → Dataset<UserEvent>", "trainALS(data, rank, iterations) → ALSModel", "computeEmbeddings(model) → Dataset<UserEmbedding>", "writeToFeatureStore(embeddings) → void"] },
      { name: "IcebergTable", methods: ["append(records) → void  // ACID write", "overwrite(filter, records) → void", "timeTravel(snapshotId) → Table  // point-in-time query", "expireSnapshots(olderThan) → void"] },
    ],
  },

  chaos: {
    title: "Chaos Engineering + Hystrix", category: "Reliability", color: "#94a3b8",
    description: "Netflix invented chaos engineering — they randomly kill production instances, introduce latency, and take down entire AWS regions to prove the system handles failure gracefully. Hystrix circuit breakers wrap every inter-service call with a fallback. Kayenta performs automated canary analysis on every deployment, auto-rolling back if metrics degrade.",
    responsibilities: [
      "Chaos Monkey: randomly kill EC2 instances in production",
      "Chaos Kong: terminate entire AWS region",
      "Latency Monkey: inject artificial 100-5000ms delays on service calls",
      "Conformity Monkey: flag instances violating best practices",
      "Security Monkey: scan for security misconfigurations",
      "Hystrix: circuit breaker on every downstream call",
      "Kayenta: canary analysis on every deploy → auto-rollback",
      "Archaius: dynamic config without restart (kill switch for features)",
    ],
    tech: ["Simian Army (Netflix OSS)", "Hystrix (circuit breaker, open-sourced)", "Kayenta (canary analysis, open-sourced)", "Archaius (dynamic config)", "Spinnaker (CD + canary deployment)"],
    classes: [
      { name: "HystrixCommand<T>", methods: ["run() → T  // calls downstream service", "getFallback() → T  // returns degraded/cached response", "execute() → T  // sync: run() or getFallback()", "queue() → Future<T>  // async execution", "observe() → Observable<T>  // reactive execution"] },
      { name: "HystrixCircuitBreaker", fields: ["state: CLOSED|OPEN|HALF_OPEN", "failureCount: AtomicInt", "failureThreshold: Int  // default 50%", "sleepWindowMs: Int  // default 5000ms", "requestVolumeThreshold: Int  // min 20 requests"], methods: ["allowRequest() → Boolean", "markSuccess() → void", "markFailure() → void", "trip() → void  // CLOSED→OPEN", "attemptExecution() → Boolean  // OPEN→HALF_OPEN probe"] },
      { name: "KayentaCanary", methods: ["deploy(canaryConfig: CanaryConfig) → DeploymentId", "analyze(deploymentId) → CanaryScore  // 0-100", "shouldRollback(score) → Boolean  // < 75 triggers rollback", "rollback(deploymentId) → void"] },
      { name: "Archaius", methods: ["getBoolean(key, default) → DynamicBooleanProperty", "getInt(key, default) → DynamicIntProperty", "getString(key, default) → DynamicStringProperty  // hot-reload, no restart"] },
    ],
    notes: "Fallback matrix: Recommendation fails → trending titles. Catalog slow → stale EVCache. DRM down → graceful 'unavailable' error. Billing unreachable → allow stream (fail open, reconcile later). Never a blank screen.",
  },
};

export type SDNode = { id: string; label: string; sub: string; icon: string; x: number; y: number; color: string };
export type SDEdge = { from: string; to: string; color: string; dur?: number };

export const VW = 1900, VH = 780;
export const NW = 122, NH = 46;

export const NODES: SDNode[] = [
  { id: "client",       label: "Client Apps",      sub: "TV·Mobile·Web",    icon: "📱", x: 100,  y: 170, color: "#e50914" },
  { id: "cdn",          label: "Open Connect",     sub: "Netflix CDN",      icon: "🌍", x: 100,  y: 390, color: "#e50914" },
  { id: "elb",          label: "AWS ELB",          sub: "Load Balancer",    icon: "⚖️",  x: 100,  y: 600, color: "#f97316" },
  { id: "eureka",       label: "Eureka + Ribbon",  sub: "Service Mesh",     icon: "🔮", x: 320,  y: 680, color: "#6366f1" },
  { id: "zuul",         label: "Zuul2 Gateway",    sub: "Auth·Rate·Route",  icon: "🔀", x: 320,  y: 170, color: "#f59e0b" },
  { id: "auth",         label: "Auth Service",     sub: "JWT·OAuth·Devices",icon: "🔐", x: 570,  y: 70,  color: "#8b5cf6" },
  { id: "user",         label: "User Service",     sub: "Profiles·History", icon: "👤", x: 570,  y: 205, color: "#3b82f6" },
  { id: "catalog",      label: "Catalog Service",  sub: "Titles·Metadata",  icon: "🎬", x: 570,  y: 340, color: "#10b981" },
  { id: "search",       label: "Search Service",   sub: "ES·Autocomplete",  icon: "🔍", x: 570,  y: 475, color: "#14b8a6" },
  { id: "download",     label: "Download Service", sub: "Offline·DRM",      icon: "📥", x: 570,  y: 610, color: "#7c3aed" },
  { id: "playback",     label: "Playback Service", sub: "Manifest·< 300ms", icon: "▶️",  x: 820,  y: 100, color: "#ef4444" },
  { id: "billing",      label: "Billing Service",  sub: "Plans·Stripe",     icon: "💳", x: 820,  y: 255, color: "#ec4899" },
  { id: "recommendation",label:"Recommendation",   sub: "ML·Two-Tower",     icon: "🤖", x: 820,  y: 410, color: "#a855f7" },
  { id: "notification", label: "Notification Svc", sub: "Push·Email·SMS",   icon: "🔔", x: 820,  y: 555, color: "#06b6d4" },
  { id: "abtest",       label: "A/B Testing (XP)", sub: "Experiments",      icon: "🧪", x: 820,  y: 690, color: "#84cc16" },
  { id: "steering",     label: "Steering Service", sub: "OCA Selection",    icon: "🧭", x: 1070, y: 130, color: "#f97316" },
  { id: "drm",          label: "DRM License Svc",  sub: "Widevine·FP·PR",   icon: "🛡️",  x: 1070, y: 290, color: "#dc2626" },
  { id: "concurrency",  label: "Concurrency Ctrl", sub: "Stream Limits",    icon: "🔒", x: 1070, y: 450, color: "#f43f5e" },
  { id: "encoding",     label: "Encoding Pipeline",sub: "1200+ variants",   icon: "⚙️",  x: 1070, y: 610, color: "#ea580c" },
  { id: "kafka",        label: "Apache Kafka",     sub: "1T events/day",    icon: "⚡", x: 1320, y: 230, color: "#f59e0b" },
  { id: "cassandra",    label: "Cassandra",        sub: "10k nodes",        icon: "🗄️",  x: 1320, y: 420, color: "#06b6d4" },
  { id: "mysql",        label: "MySQL / RDS",      sub: "ACID · Billing",   icon: "🐬", x: 1570, y: 130, color: "#3b82f6" },
  { id: "redis",        label: "Redis Cluster",    sub: "Sessions·Slots",   icon: "🔴", x: 1570, y: 290, color: "#ef4444" },
  { id: "evcache",      label: "EVCache",          sub: "30M req/s · HA",   icon: "⚡", x: 1570, y: 450, color: "#10b981" },
  { id: "analytics",    label: "Data Pipeline",    sub: "Flink·Spark·Icbrg",icon: "📊", x: 1570, y: 590, color: "#34d399" },
  { id: "chaos",        label: "Chaos + Hystrix",  sub: "Resilience",       icon: "💥", x: 1570, y: 720, color: "#94a3b8" },
];

export const EDGES: SDEdge[] = [
  { from: "client",    to: "cdn",          color: "#e50914", dur: 1.3 },
  { from: "client",    to: "elb",          color: "#f97316", dur: 1.6 },
  { from: "elb",       to: "zuul",         color: "#f59e0b", dur: 1.5 },
  { from: "elb",       to: "eureka",       color: "#6366f1", dur: 2.5 },
  { from: "zuul",      to: "auth",         color: "#8b5cf6", dur: 1.5 },
  { from: "zuul",      to: "user",         color: "#3b82f6", dur: 1.7 },
  { from: "zuul",      to: "catalog",      color: "#10b981", dur: 2.0 },
  { from: "zuul",      to: "search",       color: "#14b8a6", dur: 2.2 },
  { from: "zuul",      to: "download",     color: "#7c3aed", dur: 2.5 },
  { from: "zuul",      to: "playback",     color: "#ef4444", dur: 1.5 },
  { from: "zuul",      to: "billing",      color: "#ec4899", dur: 2.0 },
  { from: "zuul",      to: "recommendation",color: "#a855f7", dur: 2.2 },
  { from: "playback",  to: "steering",     color: "#f97316", dur: 1.5 },
  { from: "playback",  to: "drm",          color: "#dc2626", dur: 1.6 },
  { from: "playback",  to: "concurrency",  color: "#f43f5e", dur: 1.7 },
  { from: "playback",  to: "kafka",        color: "#f59e0b", dur: 1.8 },
  { from: "playback",  to: "cassandra",    color: "#06b6d4", dur: 2.0 },
  { from: "billing",   to: "kafka",        color: "#f59e0b", dur: 2.2 },
  { from: "billing",   to: "mysql",        color: "#3b82f6", dur: 2.0 },
  { from: "steering",  to: "cdn",          color: "#f97316", dur: 2.0 },
  { from: "encoding",  to: "cdn",          color: "#ea580c", dur: 2.5 },
  { from: "encoding",  to: "kafka",        color: "#f59e0b", dur: 2.8 },
  { from: "kafka",     to: "analytics",    color: "#34d399", dur: 1.8 },
  { from: "kafka",     to: "recommendation",color:"#a855f7", dur: 2.4 },
  { from: "kafka",     to: "notification", color: "#06b6d4", dur: 2.2 },
  { from: "recommendation", to: "cassandra",color:"#06b6d4",dur: 2.0 },
  { from: "recommendation", to: "evcache", color: "#10b981", dur: 1.7 },
  { from: "auth",      to: "redis",        color: "#ef4444", dur: 1.6 },
  { from: "auth",      to: "mysql",        color: "#3b82f6", dur: 2.0 },
  { from: "concurrency",to: "redis",       color: "#ef4444", dur: 1.5 },
  { from: "catalog",   to: "evcache",      color: "#10b981", dur: 1.6 },
  { from: "abtest",    to: "evcache",      color: "#10b981", dur: 2.0 },
  { from: "chaos",     to: "playback",     color: "#94a3b8", dur: 4.0 },
  { from: "eureka",    to: "zuul",         color: "#6366f1", dur: 2.8 },
  { from: "notification",to:"kafka",       color: "#06b6d4", dur: 3.0 },
];

export const LAYER_LABELS = [
  { x: 100,  label: "Client / CDN" },
  { x: 320,  label: "Gateway" },
  { x: 570,  label: "Core Services" },
  { x: 820,  label: "Platform Svcs" },
  { x: 1070, label: "Infra Layer" },
  { x: 1320, label: "Messaging / DB" },
  { x: 1570, label: "Storage / Data" },
];
