export type PipelineNodeDetail = {
  title: string;
  category: string;
  color: string;
  description: string;
  role: string[];
  tables: { name: string; columns: { col: string; type: string; note?: string }[]; pk?: string; partitionBy?: string; notes?: string }[];
  tools: string[];
  dataFlows?: { direction: "in" | "out"; from_to: string; format: string; freq: string }[];
  sla?: string;
  notes?: string;
};

export const PIPELINE_DETAILS: Record<string, PipelineNodeDetail> = {

  clickstream: {
    title: "Event SDK & Data Sources", category: "Layer 1 · Sources", color: "#e50914",
    description: "Every Netflix client device emits structured events using a common telemetry SDK. ~700B events/day, 8.1M/sec average, 15M/sec peak across 300M subscribers. The SDK batches micro-events locally (every 30s or 50 events), compresses with LZ4, and ships Avro payloads to the ingestion gateway. Offline events are queued in SQLite for replay when connectivity resumes.",
    role: [
      "Generate globally unique event_id (UUID v7) at creation time — idempotency key",
      "Client SDK maintains local ring buffer + SQLite offline queue (P1/P2 events only)",
      "Batch 20–200 events, compress, retry with exponential backoff + jitter",
      "Attach schema version, consent flags, experiment IDs, device fingerprint",
      "Priority tiers: P0 (payment/sub — never drop) → P4 (verbose diagnostics — sample aggressively)",
      "CDC sources: Aurora/RDS via Debezium, DynamoDB Streams, partner file drops via S3 Transfer",
    ],
    tables: [
      {
        name: "event_envelope (Avro schema v7)",
        pk: "event_id",
        columns: [
          { col: "event_id",          type: "UUID",        note: "v7 uuid, client-generated, idempotency key" },
          { col: "event_name",        type: "STRING",      note: "e.g. playback_buffering_started" },
          { col: "schema_version",    type: "INT",         note: "Avro schema version ID" },
          { col: "event_time",        type: "TIMESTAMP",   note: "client-side epoch ms (event time)" },
          { col: "client_send_time",  type: "TIMESTAMP",   note: "when SDK actually flushed" },
          { col: "account_token",     type: "STRING",      note: "tokenised — no raw user_id at edge" },
          { col: "profile_token",     type: "STRING" },
          { col: "device_id",         type: "STRING",      note: "hashed device fingerprint" },
          { col: "session_id",        type: "UUID" },
          { col: "playback_id",       type: "UUID",        note: "nullable — playback events only" },
          { col: "title_id",          type: "STRING",      note: "nullable" },
          { col: "country",           type: "CHAR(2)",     note: "ISO 3166-1 alpha-2" },
          { col: "device_type",       type: "ENUM",        note: "SMART_TV|MOBILE|WEB|TABLET|GAME_CONSOLE" },
          { col: "app_version",       type: "STRING" },
          { col: "experiment_ids",    type: "ARRAY<STRING>",note: "active experiment assignments" },
          { col: "privacy",           type: "STRUCT",      note: "classification, consent_version, retention_class" },
          { col: "payload",           type: "MAP<STRING,STRING>", note: "event-specific fields" },
        ],
        notes: "Avro schema enforced via Schema Registry. Incompatible schemas rejected at producer with HTTP 422.",
      },
      {
        name: "event_priorities",
        columns: [
          { col: "P0", type: "CRITICAL",  note: "payment, subscription — never drop, local persist + retry forever" },
          { col: "P1", type: "HIGH",      note: "playback start/failure — persist locally, retry within 2h" },
          { col: "P2", type: "MEDIUM",    note: "impressions, clicks — retry within bounded window" },
          { col: "P3", type: "LOW",       note: "debug telemetry — sample 10% during incidents" },
          { col: "P4", type: "VERBOSE",   note: "diagnostic logs — aggressively sampled, drop on overload" },
        ],
      },
    ],
    tools: [
      "Netflix Client SDK (iOS Swift / Android Kotlin / JS Web)",
      "Avro + Confluent Schema Registry",
      "SQLite (offline event queue on mobile)",
      "LZ4 compression",
      "Debezium (Aurora/RDS CDC)",
      "DynamoDB Streams",
      "AWS Transfer Family (partner file drops)",
      "Airbyte (SaaS data sources)",
    ],
    dataFlows: [
      { direction: "out", from_to: "→ Ingestion Gateway (HTTP/2 batch)", format: "Avro+LZ4", freq: "every 30s or 50 events" },
      { direction: "out", from_to: "→ Kafka CDC topics (Debezium)", format: "Avro", freq: "real-time change events" },
    ],
    sla: "P0/P1 events: zero loss tolerance. SDK retries up to 2h. Dead-letter rate < 0.01% of accepted events.",
    notes: "Scale: 700B events/day = ~8.1M/sec avg, 15M/sec peak. At 500B avg event size (compressed ~150B), that's ~1.5 PB/day landing in S3.",
  },

  kafka_ingest: {
    title: "Event Gateway + Kafka Backbone", category: "Layer 2–3 · Ingest + Transport", color: "#f59e0b",
    description: "Two components: (1) the Event Gateway (Zuul on EKS) validates, enriches and routes events; (2) Apache Kafka on AWS MSK is the central nervous system — ~700B events/day, 8 PB/day throughput across purpose-specific topic clusters. Schema Registry enforces Avro contracts. 7-day hot retention, then tiered to S3 via Kafka Connect. MirrorMaker 2 replicates critical topics cross-region.",
    role: [
      "Gateway: authenticate producer, validate schema, tokenise PII, bloom-filter dedup (30-min window)",
      "Gateway: GeoIP enrichment, rate limiting (per-device token bucket in Redis), route by eventType",
      "Gateway: acknowledge ONLY after Kafka write confirmed by min.insync.replicas=2",
      "Kafka: topic-per-domain clusters — playback-critical, ui-interactions, ads, cdc, service-events",
      "Schema Registry: BACKWARD_TRANSITIVE compatibility — new schema must read all previous versions",
      "Kafka Connect: continuous S3 sink to Parquet (Iceberg Bronze tables), 5-min micro-batches",
      "MirrorMaker 2: async cross-region replication for playback-critical and billing topics",
    ],
    tables: [
      {
        name: "kafka_topic_inventory",
        columns: [
          { col: "prod.playback.started.v3",         type: "topic", note: "10K partitions — keyed by playback_id, 7d TTL" },
          { col: "prod.playback.heartbeat.v5",        type: "topic", note: "10K partitions — ~200B events/day" },
          { col: "prod.playback.error.v4",            type: "topic", note: "3K partitions, 7d TTL" },
          { col: "prod.ui.impression.v7",             type: "topic", note: "5K partitions, keyed by profile_id" },
          { col: "prod.ui.click.v5",                  type: "topic", note: "5K partitions" },
          { col: "prod.recommendation.served.v4",     type: "topic", note: "2K partitions, keyed by profile_id" },
          { col: "prod.subscription.customer.v6",     type: "topic", note: "500 partitions, EXACTLY_ONCE" },
          { col: "prod.experiment.assignment.v3",     type: "topic", note: "1K partitions" },
          { col: "prod.cdc.aurora-catalog",           type: "topic", note: "100 partitions — Debezium CDC" },
          { col: "prod.*.dlq",                        type: "topic", note: "DLQ per domain, 7d TTL, Slack/PagerDuty alert" },
        ],
        notes: "Partition key rule: playback_id for playback (NOT title_id — hot partition risk). profile_id for UI. account_id for billing.",
      },
      {
        name: "kafka_cluster_config",
        columns: [
          { col: "replication_factor",          type: "3",             note: "cross-AZ, min.insync.replicas=2" },
          { col: "brokers_per_cluster",         type: "~100",          note: "keep CPU < 60% for failure headroom" },
          { col: "local_retention",             type: "6–24h",         note: "tiered storage extends to 7 days" },
          { col: "compression",                 type: "Zstd",          note: "LZ4 for ultra-low latency paths" },
          { col: "producer_acks",               type: "all",           note: "required for durability" },
          { col: "idempotence",                 type: "true",          note: "exactly-once at broker level" },
          { col: "max_in_flight",               type: "5",             note: "with idempotence enabled" },
          { col: "unclean_leader_election",     type: "disabled",      note: "never risk data loss for availability" },
        ],
      },
    ],
    tools: [
      "Apache Kafka 3.x on AWS MSK",
      "Confluent Schema Registry (BACKWARD_TRANSITIVE)",
      "Kafka Connect (S3 Iceberg sink)",
      "Kafka MirrorMaker 2 (cross-region)",
      "Netflix Zuul Gateway (EKS)",
      "Debezium (MySQL/Aurora CDC)",
      "Burrow (consumer lag monitoring)",
      "AWS MSK Tiered Storage",
    ],
    dataFlows: [
      { direction: "in",  from_to: "← Event SDK (all device types)",      format: "Avro",    freq: "real-time, 8M+/sec" },
      { direction: "in",  from_to: "← Debezium CDC (Aurora/RDS)",         format: "Avro",    freq: "real-time change events" },
      { direction: "out", from_to: "→ Flink streaming jobs",               format: "Avro",    freq: "real-time" },
      { direction: "out", from_to: "→ S3 Bronze (Kafka Connect)",          format: "Parquet", freq: "5-min micro-batch" },
      { direction: "out", from_to: "→ Druid real-time ingestion",          format: "JSON",    freq: "real-time" },
      { direction: "out", from_to: "→ Direct consumers (fraud, notif, recs)", format: "Avro", freq: "real-time" },
    ],
    sla: "Producer P99 latency < 20ms. Consumer lag alert threshold: 10 minutes. DLQ rate > 0.1% triggers PagerDuty.",
    notes: "Throughput math: 15M events/sec × 500B = 7.5 GB/sec × 3 (replication) = 22.5 GB/sec write. 100 brokers × 10Gb NIC = 1 TB/sec capacity — run at ~30% utilisation.",
  },

  flink: {
    title: "Flink Stream Processing", category: "Layer 4 · Real-time Processing", color: "#ef4444",
    description: "Apache Flink on EKS is the real-time processing engine — true streaming (event-by-event, not micro-batch). Handles session stitching, QoE monitoring, fraud detection, A/B test aggregation, and online feature generation. RocksDB state backend on EBS gp3 with incremental checkpoints to S3 every 30s. Exactly-once via 2-phase commit with Kafka. Watermark: 30s allowed lateness; late events go to side-output correction stream.",
    role: [
      "Session stitching: group raw events into user sessions using 30-min inactivity timeout",
      "QoE monitor: detect rebuffering ratio > 5% per region/device — trigger CDN switch within 200ms",
      "Fraud detector: account takeover signals (new device + geo anomaly + rapid login attempts)",
      "A/B aggregator: real-time experiment metrics (CTR, stream start rate) per variant — feeds Druid",
      "Feature generator: compute user context features (last 5 titles, current genre affinity) → Redis/Cassandra",
      "Content popularity: rolling 1-hour trending titles per country — feeds recommendation fallback",
      "Deduplication: keyBy(event_id), state TTL=24h — catches SDK retry duplicates",
      "Late data: 5-min watermark for most jobs; extremely late events → correction topic → nightly batch fix",
    ],
    tables: [
      {
        name: "playback_session (Flink output → Kafka + Iceberg Silver)",
        pk: "session_id",
        columns: [
          { col: "session_id",           type: "UUID" },
          { col: "playback_id",          type: "UUID" },
          { col: "profile_id",           type: "UUID" },
          { col: "title_id",             type: "UUID" },
          { col: "session_start_ts",     type: "TIMESTAMP" },
          { col: "session_end_ts",       type: "TIMESTAMP" },
          { col: "startup_time_ms",      type: "BIGINT",    note: "time from play-click to first frame" },
          { col: "total_watch_ms",       type: "BIGINT" },
          { col: "rebuffer_count",       type: "INT" },
          { col: "rebuffer_total_ms",    type: "BIGINT" },
          { col: "rebuffer_ratio",       type: "DOUBLE",    note: "rebuffer_ms / total_watch_ms" },
          { col: "avg_bitrate_kbps",     type: "INT" },
          { col: "bitrate_switches",     type: "INT" },
          { col: "final_status",         type: "ENUM",      note: "COMPLETED|ABANDONED|ERROR" },
          { col: "error_code",           type: "STRING",    note: "nullable" },
          { col: "device_type",          type: "STRING" },
          { col: "country",              type: "CHAR(2)" },
          { col: "window_end_ts",        type: "TIMESTAMP", note: "Flink event-time window close" },
        ],
        notes: "Flink session window: keyBy(playback_id), 30-min inactivity gap. Late tolerance: 5 minutes.",
      },
      {
        name: "flink_cluster_config",
        columns: [
          { col: "job_managers",     type: "3",           note: "HA via ZooKeeper/K8s leader election" },
          { col: "task_managers",    type: "500+ nodes",  note: "On-Demand for stateful, Spot for stateless" },
          { col: "default_parallelism", type: "2,000" },
          { col: "checkpoint_interval", type: "30s",      note: "incremental RocksDB to S3" },
          { col: "state_backend",    type: "RocksDB",     note: "on EBS gp3 — incremental checkpoints" },
          { col: "watermark_lag",    type: "30s",         note: "allowedLateness for most jobs" },
          { col: "late_data",        type: "side output", note: "→ correction Kafka topic → nightly batch fix" },
          { col: "exactly_once",     type: "2PC + KafkaSink", note: "Flink checkpoints atomically with Kafka commit" },
        ],
      },
    ],
    tools: [
      "Apache Flink 1.18 on EKS (Flink Kubernetes Operator)",
      "RocksDB state backend (on EBS gp3)",
      "S3 checkpointing + savepoints",
      "Flink SQL",
      "AWS Kinesis Data Analytics (managed Flink option)",
      "Netflix Mantis (self-serve ad-hoc streaming queries)",
    ],
    dataFlows: [
      { direction: "in",  from_to: "← Kafka topics (all domains)",      format: "Avro",    freq: "real-time" },
      { direction: "out", from_to: "→ Kafka enriched topics",            format: "Avro",    freq: "real-time" },
      { direction: "out", from_to: "→ Iceberg Silver (sessions, dedup)", format: "Parquet", freq: "on window close" },
      { direction: "out", from_to: "→ Druid (real-time QoE rollup)",     format: "JSON",    freq: "real-time" },
      { direction: "out", from_to: "→ Redis (user context features)",    format: "JSON",    freq: "< 2min" },
      { direction: "out", from_to: "→ PagerDuty (QoE anomaly alerts)",   format: "webhook", freq: "on threshold breach" },
    ],
    sla: "End-to-end latency < 500ms. Checkpoint recovery RTO < 2min. QoE alert to CDN switch < 200ms.",
    notes: "Mantis (Netflix OSS): engineers submit live SQL-like queries against Kafka streams in < 30 seconds — self-serve operational analytics without a central team.",
  },

  s3_lake: {
    title: "S3 Data Lake · Apache Iceberg", category: "Layer 5 · Storage", color: "#3b82f6",
    description: "S3 is the immutable source of truth — ~1.5 PB/day compressed, ~60+ PB total. Apache Iceberg provides ACID transactions, time-travel queries, schema evolution, and hidden partitioning on plain S3 objects. Netflix organises data in a Medallion architecture: Landing → Bronze → Silver → Gold → Feature/ML. Iceberg's snapshot-based commits mean a batch job can be safely retried — idempotent by design. AWS Glue Catalog is the primary metastore.",
    role: [
      "Landing zone: raw Avro/JSON from Kafka Connect — immutable, short retention, used for replay/recovery",
      "Bronze: minimal transformation, event-level, append-only, preserves source fidelity",
      "Silver: validated, deduped (ROW_NUMBER over event_id), tokenised, sessionised, enriched",
      "Gold: business-ready aggregations — playback QoE, recommendation funnel, revenue, content engagement",
      "Feature/ML: point-in-time-correct ML features, training datasets, model scores",
      "Iceberg maintenance: hourly compaction (128MB→1GB files), manifest rewrite, snapshot expiry",
      "Partition evolution: change partitioning (e.g. days→hours) without rewriting data",
    ],
    tables: [
      {
        name: "silver.playback_session (Iceberg)",
        pk: "session_id",
        partitionBy: "hours(session_start_ts), bucket(256, profile_id)",
        columns: [
          { col: "session_id",           type: "UUID",      note: "dedup key" },
          { col: "profile_id",           type: "UUID" },
          { col: "title_id",             type: "UUID" },
          { col: "session_start_ts",     type: "TIMESTAMP", note: "Iceberg partition column (hidden)" },
          { col: "total_watch_ms",       type: "BIGINT" },
          { col: "rebuffer_ratio",       type: "DOUBLE" },
          { col: "avg_bitrate_kbps",     type: "INT" },
          { col: "final_status",         type: "STRING" },
          { col: "device_type",          type: "STRING" },
          { col: "country",              type: "CHAR(2)" },
          { col: "ingested_at",          type: "TIMESTAMP", note: "S3 write time" },
        ],
        notes: "Sort order: country, device_type, title_id, session_start_ts — optimises common filter patterns. File target: 512MB Parquet.",
      },
      {
        name: "s3_storage_zones",
        columns: [
          { col: "s3://netflix-landing/", type: "zone", note: "raw Avro — 1–3 day retention" },
          { col: "s3://netflix-bronze/",  type: "zone", note: "event-level Parquet — 7d hot, 30d IA, 1yr archive" },
          { col: "s3://netflix-silver/",  type: "zone", note: "enriched sessions — 30–90d Standard, 18mo IA" },
          { col: "s3://netflix-gold/",    type: "zone", note: "aggregations — 12–24mo Standard" },
          { col: "s3://netflix-features/",type: "zone", note: "ML feature snapshots — 13mo retention" },
          { col: "s3://netflix-audit/",   type: "zone", note: "immutable compliance log — 7–10yr" },
          { col: "s3://netflix-quarantine/",type:"zone",note: "invalid events — 7d, replay after fix" },
        ],
        notes: "S3 Intelligent Tiering auto-moves cold objects. Iceberg compaction: merge 10K small files → 100 large files → 90% less S3 LIST/GET cost.",
      },
    ],
    tools: [
      "Apache Iceberg 1.5 (table format)",
      "AWS S3 (object storage)",
      "AWS Glue Data Catalog (Iceberg REST catalog)",
      "Kafka Connect (S3 sink — Bronze landing)",
      "Apache Parquet + Zstd compression",
      "AWS S3 Intelligent Tiering",
      "Trino / Spark / Flink (multi-engine reads)",
    ],
    dataFlows: [
      { direction: "in",  from_to: "← Kafka Connect (Bronze landing)",   format: "Parquet",   freq: "5-min micro-batch" },
      { direction: "in",  from_to: "← Flink (Silver session writes)",    format: "Parquet",   freq: "on window close" },
      { direction: "in",  from_to: "← Spark ETL (Gold + Feature)",       format: "Parquet",   freq: "hourly / nightly" },
      { direction: "out", from_to: "→ Spark EMR (batch reads)",          format: "Parquet",   freq: "scheduled" },
      { direction: "out", from_to: "→ Trino / Athena (ad-hoc SQL)",      format: "Parquet",   freq: "on query" },
      { direction: "out", from_to: "→ Druid (historical backfill)",       format: "Parquet",   freq: "on demand" },
    ],
    sla: "Kafka Connect lag < 5min. Silver tables available within 15min of event time. Gold tables ready by 07:00 UTC. Iceberg compaction: hourly.",
    notes: "Time-travel: SELECT * FROM silver.playback_session FOR SYSTEM_TIME AS OF '2024-01-15 00:00:00' — used to reproduce exact A/B cohort state and GDPR deletion verification.",
  },

  airflow: {
    title: "Workflow Orchestration · Airflow / Maestro", category: "Layer 6 · Orchestration", color: "#84cc16",
    description: "Netflix uses Apache Airflow (AWS MWAA) for standard batch pipelines and its own Maestro (open-sourced) for large-scale, horizontally-scalable ML and data workflows. 800+ production DAGs. Every DAG is version-controlled in GitHub and deployed via CI/CD. KafkaSensors wait for upstream lag to drain before triggering Spark jobs — prevents reading incomplete hourly partitions.",
    role: [
      "DAG per pipeline: nightly_rec_train, daily_enriched_plays, hourly_qoe_rollup, encoding_quality",
      "SLA miss callbacks → PagerDuty alert if job misses deadline",
      "ExternalTaskSensor: wait for upstream DAG completion before starting dependent jobs",
      "KafkaSensor: poll consumer lag — start Spark only when lag < threshold (complete hourly window)",
      "Dynamic task mapping: one Spark job per region (us / eu / apac) — parallelise backfills",
      "Backfill isolation: separate queues, lower priority, read/write rate limits, explicit approval for publish",
      "Incremental processing: store input_snapshot_id + output_snapshot_id per run — safe retry",
    ],
    tables: [
      {
        name: "airflow_dag_catalogue (key pipelines)",
        columns: [
          { col: "iceberg_hourly_compaction",  type: "DAG", note: "every hour — merge small files, rewrite manifests, expire snapshots" },
          { col: "daily_silver_enrichment",    type: "DAG", note: "01:00 UTC — dedup + session join → Silver tables" },
          { col: "daily_gold_aggregations",    type: "DAG", note: "02:00 UTC — QoE rollup, rec funnel, revenue → Gold" },
          { col: "nightly_rec_train",          type: "DAG", note: "02:30 UTC — Spark ALS + two-tower training → Cassandra" },
          { col: "nightly_feature_materialise",type: "DAG", note: "04:00 UTC — push Gold features → Feast online (Redis/DynamoDB)" },
          { col: "ab_test_daily_settlement",   type: "DAG", note: "06:00 UTC — t-test / CUPED variance reduction → Druid/Redshift" },
          { col: "billing_monthly_rollup",     type: "DAG", note: "1st of month — revenue reconciliation → Finance Redshift" },
          { col: "gdpr_deletion_cascade",      type: "DAG", note: "on request — Iceberg DELETE + Cassandra + Redis purge" },
        ],
        notes: "All DAGs in GitHub. Merge to main = deploy. Backfill jobs isolated in separate Airflow pool — never starve production.",
      },
    ],
    tools: [
      "Apache Airflow 2.8 (AWS MWAA)",
      "Netflix Maestro (horizontally-scalable ML workflows)",
      "Netflix Conductor (microservice workflows)",
      "GitHub Actions (DAG CI/CD)",
      "PagerDuty (SLA alerts)",
      "KafkaSensor (wait for partition completeness)",
    ],
    dataFlows: [
      { direction: "in",  from_to: "← GitHub (DAG definitions)",        format: "Python",  freq: "on merge" },
      { direction: "in",  from_to: "← Kafka (lag metrics via sensor)",  format: "metrics", freq: "polling" },
      { direction: "out", from_to: "→ Spark EMR (job triggers)",        format: "AWS API", freq: "scheduled" },
      { direction: "out", from_to: "→ SageMaker (training triggers)",   format: "AWS API", freq: "nightly" },
    ],
    sla: "SLA miss < 1% of DAG runs. Critical DAGs (rec_train, gold_aggregations) hard SLA: 05:00 UTC. Breach = PagerDuty P1.",
  },

  spark: {
    title: "Spark on EMR · Batch Processing", category: "Layer 6 · Batch", color: "#f97316",
    description: "Apache Spark on AWS EMR handles all large-scale batch workloads that are too expensive for real-time: 90-day recommendation model training, VMAF encoding quality scoring, SCD Type 2 dimension processing, subscriber churn modelling, financial reconciliation, and A/B test final settlement. Jobs read from Iceberg Silver/Bronze and write Gold tables + ML features. 70% of task nodes run on Spot Instances.",
    role: [
      "ALS matrix factorisation: 90-day user × item matrix, rank=256, 20 iterations — produces user/item embeddings",
      "Enriched plays fact table: JOIN playback_sessions + catalog + billing → denormalised analytics table",
      "SCD Type 2 on dim_users: plan upgrades create new row — accurate historical revenue attribution",
      "VMAF quality scoring: compute perceptual quality scores per encoding variant — feeds encoding feedback loop",
      "Churn prediction features: engagement decay signals, cancel intent patterns, lifetime value",
      "A/B test settlement: t-test / Mann-Whitney U + CUPED variance reduction at day close",
      "Iceberg maintenance: compaction, manifest rewrite, snapshot expiry, orphan file cleanup",
    ],
    tables: [
      {
        name: "gold.enriched_plays (daily fact table)",
        pk: "play_id",
        partitionBy: "date(session_start_ts)",
        columns: [
          { col: "play_id",           type: "UUID",    note: "surrogate key" },
          { col: "user_sk",           type: "BIGINT",  note: "FK → dim_users.user_sk (SCD2)" },
          { col: "title_sk",          type: "BIGINT",  note: "FK → dim_titles.title_sk" },
          { col: "date_sk",           type: "INT",     note: "YYYYMMDD — FK → dim_dates" },
          { col: "total_watch_ms",    type: "BIGINT" },
          { col: "completion_pct",    type: "DOUBLE" },
          { col: "rebuffer_ratio",    type: "DOUBLE" },
          { col: "avg_bitrate_kbps",  type: "INT" },
          { col: "device_type",       type: "STRING" },
          { col: "country",           type: "CHAR(2)" },
          { col: "plan",              type: "STRING",  note: "from SCD2 dim_users — plan at time of watch" },
          { col: "experiment_variant",type: "STRING",  note: "null if not in experiment" },
          { col: "content_type",      type: "STRING",  note: "MOVIE|SERIES|DOCUMENTARY|STANDUP" },
          { col: "genre",             type: "STRING",  note: "primary genre — denormalised" },
          { col: "date",              type: "DATE",    note: "Iceberg partition column" },
        ],
        notes: "~2B rows/day. Used by Tableau, Trino, and ML feature pipelines. SCD2 join preserves plan at time-of-watch — critical for accurate revenue attribution.",
      },
      {
        name: "emr_cluster_config",
        columns: [
          { col: "master",           type: "r5.4xlarge × 3",  note: "HA" },
          { col: "core_workers",     type: "200 × r5.12xlarge", note: "On-Demand, persistent" },
          { col: "task_workers",     type: "500 × Spot i3.4xlarge", note: "ephemeral, 70% cost saving" },
          { col: "executor_size",    type: "4 cores / 16GB",   note: "per Spark executor" },
          { col: "dynamic_alloc",    type: "min 200 / max 2000" },
          { col: "aqe",              type: "enabled",          note: "Adaptive Query Execution — auto-fixes skew" },
          { col: "iceberg_ext",      type: "IcebergSparkSessionExtensions" },
        ],
      },
    ],
    tools: [
      "Apache Spark 3.5 on AWS EMR 7.x",
      "PySpark + Spark SQL",
      "EMR on EKS (Kubernetes native)",
      "AWS Spot Instances (70% task nodes)",
      "Apache Iceberg (source + sink)",
      "AWS Glue Catalog",
      "Adaptive Query Execution (AQE)",
    ],
    dataFlows: [
      { direction: "in",  from_to: "← Iceberg Silver (session, activity)", format: "Parquet", freq: "nightly / hourly" },
      { direction: "in",  from_to: "← Iceberg Bronze (replay/backfill)",   format: "Parquet", freq: "on backfill" },
      { direction: "out", from_to: "→ Iceberg Gold (enriched_plays, agg)", format: "Parquet", freq: "nightly" },
      { direction: "out", from_to: "→ Cassandra (user/item embeddings)",   format: "CQL",     freq: "nightly" },
      { direction: "out", from_to: "→ Feature store offline (S3)",         format: "Parquet", freq: "nightly" },
    ],
    sla: "Nightly ALS job completes by 03:30 UTC. Gold tables ready by 05:00 UTC. Backfill jobs must not impact production — isolated pool, rate-limited.",
    notes: "Skew prevention: Adaptive Query Execution auto-splits hot partitions. For title_id skew (viral content), salt with rand(100) then reaggregate. Null user_ids (anonymous) processed separately.",
  },

  druid: {
    title: "Apache Druid · Interactive OLAP", category: "Layer 7 · Serving", color: "#f43f5e",
    description: "Sub-second OLAP queries on billions of rows for operations teams and live dashboards. Druid ingests directly from Kafka (< 1s freshness) and from S3 Parquet (historical backfill). Pre-aggregates metrics at ingest time via rollup — 700B raw events/day compress to ~14B rollup rows without losing per-minute granularity. Powers live A/B test monitoring, encoding quality drill-downs, and QoE dashboards.",
    role: [
      "Real-time Kafka ingestion: playback QoE metrics refresh every 30s for ops dashboards",
      "Historical S3 Parquet ingestion: backfill when pipeline is late or bug-fixed",
      "Rollup at ingest: SUM play counts per (1-min bucket, region, device_type, title_id) — 50:1 compression",
      "Bitmap indexes on all dimension columns: fast GROUP BY + WHERE on country/device/title",
      "Live A/B dashboards: play_rate per experiment variant, completions, rebuffer rate — 30s refresh",
      "Encoding quality drill-down: VMAF p50/p99 per codec × resolution × region",
    ],
    tables: [
      {
        name: "playback_rollup (Druid datasource)",
        partitionBy: "HOUR (segment granularity)",
        columns: [
          { col: "__time",            type: "TIMESTAMP",  note: "Druid primary time column (1-min truncation)" },
          { col: "region",            type: "STRING",     note: "dimension — bitmap indexed" },
          { col: "country",           type: "CHAR(2)",    note: "dimension" },
          { col: "device_type",       type: "STRING",     note: "dimension" },
          { col: "title_id",          type: "STRING",     note: "dimension" },
          { col: "experiment_id",     type: "STRING",     note: "dimension — null if not in experiment" },
          { col: "variant",           type: "STRING",     note: "dimension" },
          { col: "play_count",        type: "LONG SUM",   note: "rollup metric" },
          { col: "rebuffer_ms_sum",   type: "LONG SUM",   note: "rollup metric — divide by play_count for ratio" },
          { col: "watch_ms_sum",      type: "LONG SUM",   note: "rollup metric" },
          { col: "error_count",       type: "LONG SUM",   note: "rollup metric" },
          { col: "bitrate_kbps_sum",  type: "LONG SUM",   note: "rollup metric" },
        ],
        notes: "Rollup ratio ~50:1. 700B raw events → ~14B rollup rows/day. Segment size: 1 hour. Historical segments in S3 deep storage. Replication: 2 Historical nodes per segment.",
      },
    ],
    tools: [
      "Apache Druid 28 (Kubernetes deployment)",
      "Kafka real-time ingest spec",
      "S3 deep storage (historical segments)",
      "Imply Platform (managed Druid option)",
      "Turnilo / Apache Superset (query UI)",
      "Druid SQL (JDBC / REST)",
    ],
    dataFlows: [
      { direction: "in",  from_to: "← Kafka (real-time rollup)",      format: "JSON/Avro", freq: "real-time, < 1s" },
      { direction: "in",  from_to: "← Flink (pre-aggregated metrics)", format: "JSON",     freq: "real-time" },
      { direction: "in",  from_to: "← S3 Parquet (historical)",       format: "Parquet",   freq: "on backfill" },
      { direction: "out", from_to: "→ Ops dashboards / Superset",     format: "SQL/REST",  freq: "on query" },
      { direction: "out", from_to: "→ A/B test platform (live metrics)",format: "REST API", freq: "every 30s" },
    ],
    sla: "P99 query < 2s on last 7 days data. Historical queries (90 days) < 10s. Kafka-to-Druid lag < 1s.",
  },

  feature_store: {
    title: "ML Feature Store · Feast", category: "Layer 8 · ML Platform", color: "#a855f7",
    description: "Centralised feature repository decoupling feature computation (done once in Spark/Flink) from model serving (done at < 5ms). Two-tier: offline store (S3 Iceberg — point-in-time correct, for training) and online store (Redis + DynamoDB — for real-time inference). ~50,000 named features in the catalog. Feature versioning: every model training run logs the exact feature snapshot used — enables exact reproduction and GDPR compliance.",
    role: [
      "Offline store: S3 Parquet (Iceberg) — point-in-time correct joins for training, no data leakage",
      "Online store: Redis (hot scalar features < 1ms) + DynamoDB (large vectors, embedding lookups < 5ms)",
      "Feature pipelines: Spark computes daily batch features, Flink computes real-time context features",
      "Feature versioning: model training logs feature_version → enables exact reproduction",
      "Training/serving skew prevention: same Python feature definition generates both offline + online values",
      "Feature catalog: owner, freshness SLA, lineage, PII classification — searchable via DataHub",
    ],
    tables: [
      {
        name: "user_features (online: Redis hot scalars)",
        pk: "profile_id",
        columns: [
          { col: "profile_id",           type: "STRING",           note: "Redis key — TTL = 6h" },
          { col: "recent_titles_5",      type: "LIST<STRING>",     note: "last 5 watched title IDs — real-time Flink" },
          { col: "current_genre",        type: "STRING",           note: "genre of current session" },
          { col: "session_depth",        type: "INT",              note: "episodes watched this session" },
          { col: "churn_risk_score",     type: "FLOAT",            note: "0.0–1.0, nightly Spark model" },
          { col: "preferred_hour",       type: "INT",              note: "peak viewing hour 0–23" },
        ],
        notes: "Flink updates recent_titles_5 in real-time (< 2min lag). Spark updates churn_risk_score nightly.",
      },
      {
        name: "user_embeddings (online: DynamoDB)",
        pk: "profile_id",
        columns: [
          { col: "profile_id",           type: "STRING",           note: "partition key" },
          { col: "embedding_256",        type: "BINARY",           note: "256-dim ALS float32 vector (nightly)" },
          { col: "genre_affinity",       type: "MAP<STRING,FLOAT>",note: "genre → watch_fraction, last 30d" },
          { col: "completion_rate",      type: "FLOAT",            note: "fraction of started titles completed" },
          { col: "device_preference",    type: "STRING",           note: "most-used device type" },
          { col: "computed_at",          type: "TIMESTAMP" },
          { col: "feature_version",      type: "STRING",           note: "links to model training run" },
        ],
        notes: "P99 DynamoDB read < 5ms. Embeddings updated nightly by Spark ALS job. Real-time context features updated by Flink.",
      },
      {
        name: "title_features (online: DynamoDB)",
        pk: "title_id",
        columns: [
          { col: "title_id",             type: "STRING" },
          { col: "embedding_256",        type: "BINARY",           note: "ALS item embedding (nightly)" },
          { col: "popularity_score",     type: "FLOAT",            note: "global plays last 7d, normalised" },
          { col: "trending_rank",        type: "INT",              note: "1=most trending, null if not trending" },
          { col: "avg_completion_pct",   type: "FLOAT",            note: "computed by Spark on Gold layer" },
        ],
      },
    ],
    tools: [
      "Feast (feature store framework)",
      "Apache Spark (offline feature computation)",
      "Apache Flink (real-time feature updates)",
      "Redis Cluster (online hot features, < 1ms)",
      "AWS DynamoDB (online feature vectors, < 5ms)",
      "S3 Iceberg (offline store — point-in-time correct)",
      "MLflow (model ↔ feature version tracking)",
      "DataHub (feature catalog + lineage)",
    ],
    dataFlows: [
      { direction: "in",  from_to: "← Spark (nightly batch features)",      format: "Parquet", freq: "nightly" },
      { direction: "in",  from_to: "← Flink (real-time context features)",  format: "JSON",    freq: "< 2min" },
      { direction: "out", from_to: "→ Recommendation Service (online)",     format: "DynamoDB/Redis", freq: "< 5ms p99" },
      { direction: "out", from_to: "→ Model training (offline S3 snapshot)",format: "Parquet", freq: "on training run" },
    ],
    sla: "Online feature read p99 < 5ms (DynamoDB), < 1ms (Redis). Nightly batch features complete by 04:30 UTC.",
    notes: "Point-in-time correctness: for training label at timestamp T, only features with feature_time ≤ T are joined. Prevents future data leakage and ensures training ≡ serving behaviour.",
  },

  rec_model: {
    title: "Recommendation Model Training", category: "Layer 8 · ML Platform", color: "#ec4899",
    description: "Two-tower neural network + ALS matrix factorisation trained on 90 days of user_activity. Spark ALS generates 256-dim embeddings. Two-tower TensorFlow model fine-tunes with contextual signals. Netflix Metaflow manages the ML workflow. MLflow tracks all experiments. Pre-computed scores written to Cassandra (top-500 recs per profile, read in < 5ms). Canary rollout: shadow → 1% → 5% → 20% → 100%. NDCG@10 regression > 2% → auto-rollback.",
    role: [
      "ALS: 90-day user × item interaction matrix, rank=256, 20 iterations, negative sampling (5:1)",
      "Two-tower NN: user embedding × item embedding → dot-product score, trained with in-batch negatives",
      "Evaluation: offline NDCG@10 on held-out week + online A/B test before full rollout",
      "Batch scoring: top-500 recs per profile written to Cassandra nightly — homepage served < 5ms",
      "Artwork personalisation: separate multi-armed bandit (UCB) per title × user segment",
      "Shadow deployment: new model served in parallel, no user impact, metrics collected for 24h",
      "Champion/challenger: CUPED variance reduction for accurate lift measurement",
    ],
    tables: [
      {
        name: "precomputed_recs (Cassandra — the serving table)",
        pk: "(profile_id, row_type, rank)",
        columns: [
          { col: "profile_id",      type: "UUID",      note: "partition key — all recs for a profile in one read" },
          { col: "row_type",        type: "TEXT",      note: "TWO_TOWER|TRENDING|BECAUSE_YOU_WATCHED|TOP10" },
          { col: "rank",            type: "INT",       note: "clustering key (1 = top recommendation)" },
          { col: "title_id",        type: "UUID" },
          { col: "score",           type: "FLOAT" },
          { col: "artwork_variant", type: "STRING",    note: "A/B tested thumbnail per user segment (UCB bandit)" },
          { col: "computed_at",     type: "TIMESTAMP" },
          { col: "model_version",   type: "STRING",    note: "links to MLflow run_id" },
        ],
        notes: "Top 500 pre-computed per profile. Homepage render reads Cassandra in < 5ms. Rows expire after 26h — triggers fallback to trending if Spark job is late.",
      },
      {
        name: "model_registry (MLflow)",
        columns: [
          { col: "run_id",            type: "UUID" },
          { col: "model_name",        type: "STRING",  note: "als_embeddings | two_tower_rec | artwork_bandit" },
          { col: "version",           type: "INT" },
          { col: "stage",             type: "ENUM",    note: "STAGING|PRODUCTION|ARCHIVED" },
          { col: "ndcg_at_10",        type: "DOUBLE",  note: "offline eval metric — must beat champion by > 0%" },
          { col: "feature_version",   type: "STRING",  note: "exact Feast feature snapshot used for training" },
          { col: "training_date",     type: "DATE" },
          { col: "artifact_s3_uri",   type: "STRING" },
        ],
      },
    ],
    tools: [
      "Netflix Metaflow (ML workflow orchestration)",
      "Apache Spark ALS (PySpark MLlib)",
      "TensorFlow (two-tower neural network)",
      "MLflow (experiment tracking + model registry)",
      "AWS SageMaker (GPU training — p3.16xlarge)",
      "Cassandra (pre-computed serving layer)",
      "Feast (feature retrieval — point-in-time correct)",
    ],
    dataFlows: [
      { direction: "in",  from_to: "← Feature store (user + title embeddings)", format: "Parquet/DynamoDB", freq: "nightly" },
      { direction: "in",  from_to: "← Iceberg Gold (user_activity 90d)",        format: "Parquet",          freq: "nightly" },
      { direction: "out", from_to: "→ MLflow model registry",                   format: "artifact",         freq: "per run" },
      { direction: "out", from_to: "→ Cassandra (precomputed_recs top-500)",    format: "CQL write",        freq: "nightly" },
      { direction: "out", from_to: "→ Kafka (prediction + impression events)",  format: "Avro",             freq: "real-time serving" },
    ],
    sla: "Training + scoring complete by 04:30 UTC. NDCG@10 regression > 2% → auto-rollback to previous model. Cassandra write complete before 05:00 UTC.",
    notes: "Artwork personalisation: a romance viewer sees a couple; an action viewer sees an explosion — same title, different thumbnail, determined by UCB multi-armed bandit. ~20% uplift in CTR.",
  },

  data_warehouse: {
    title: "Data Warehouse · dbt + Redshift", category: "Layer 9 · Analytics", color: "#8b5cf6",
    description: "The curated, business-facing layer built by Spark batch jobs and managed by dbt. Star schema: fact_plays at the centre, dim_users (SCD Type 2), dim_titles, dim_dates. Netflix analysts, data scientists, and finance teams query via Trino/Presto (ad-hoc) and Tableau (dashboards). dbt manages transformation lineage, tests, and documentation. Column-level security on PII fields via Lake Formation.",
    role: [
      "Star schema: fact_plays + dim_users (SCD2) + dim_titles + dim_dates",
      "SCD Type 2 on dim_users: plan upgrade creates new row — accurate historical revenue attribution",
      "dbt models: stg_playback → int_sessions → fact_plays with explicit dependency DAG",
      "dbt tests: not_null, unique PKs, accepted_values, referential integrity — block publish on failure",
      "Pre-aggregate: title_engagement_daily, country_revenue_monthly, experiment_lift_daily",
      "Column-level security: email, payment_method masked for non-finance roles (AWS Lake Formation)",
    ],
    tables: [
      {
        name: "fact_plays (star schema centre)",
        pk: "play_id",
        partitionBy: "date",
        columns: [
          { col: "play_id",            type: "UUID",    note: "surrogate key" },
          { col: "user_sk",            type: "BIGINT",  note: "FK → dim_users.user_sk (SCD2)" },
          { col: "title_sk",           type: "BIGINT",  note: "FK → dim_titles.title_sk" },
          { col: "date_sk",            type: "INT",     note: "FK → dim_dates.date_sk (YYYYMMDD)" },
          { col: "watch_ms",           type: "BIGINT" },
          { col: "completion_pct",     type: "DOUBLE" },
          { col: "rebuffer_ratio",     type: "DOUBLE" },
          { col: "avg_bitrate_kbps",   type: "INT" },
          { col: "device_type",        type: "STRING" },
          { col: "country",            type: "CHAR(2)" },
          { col: "experiment_variant", type: "STRING",  note: "null if not in experiment" },
        ],
      },
      {
        name: "dim_users (SCD Type 2)",
        pk: "user_sk",
        columns: [
          { col: "user_sk",        type: "BIGINT",  note: "surrogate key (auto-increment)" },
          { col: "user_id",        type: "UUID",    note: "natural key" },
          { col: "plan",           type: "STRING",  note: "BASIC|STANDARD|PREMIUM" },
          { col: "country",        type: "CHAR(2)" },
          { col: "effective_from", type: "DATE",    note: "SCD2 window start" },
          { col: "effective_to",   type: "DATE",    note: "null = current record" },
          { col: "is_current",     type: "BOOLEAN" },
        ],
        notes: "SCD2: plan upgrade inserts a new row. Joining fact_plays to dim_users on user_sk gives the plan at time-of-watch — not just current plan.",
      },
    ],
    tools: [
      "dbt (transformations, tests, lineage docs)",
      "AWS Redshift Serverless (structured BI queries)",
      "Trino / Presto (ad-hoc SQL on Iceberg)",
      "Tableau (dashboards — finance, content, product)",
      "AWS Lake Formation (column-level security)",
      "Great Expectations (pre-publish data quality)",
    ],
    dataFlows: [
      { direction: "in",  from_to: "← Spark (gold.enriched_plays)",        format: "Parquet", freq: "nightly" },
      { direction: "out", from_to: "→ Trino / Athena (analyst ad-hoc)",    format: "SQL",     freq: "on demand" },
      { direction: "out", from_to: "→ Tableau (scheduled refresh)",        format: "JDBC",    freq: "every 30min" },
      { direction: "out", from_to: "→ Feature store (analyst-computed features)", format: "Parquet", freq: "nightly" },
    ],
    sla: "DW tables available by 06:00 UTC. dbt test failures block table promotion to production schema.",
    notes: "dbt lineage: fact_plays ← int_sessions ← stg_playback_events + stg_users + dim_titles. Breaking upstream change = downstream table flagged stale in DataHub.",
  },

  presto: {
    title: "Trino / Presto · Ad-hoc SQL + BI", category: "Layer 9 · Analytics", color: "#14b8a6",
    description: "Distributed SQL engine that reads directly from S3 Iceberg tables, Cassandra, Aurora, and OpenSearch in a single federated query — no data movement. Netflix serves ~10,000 analytical users across products: analysts use Trino for ad-hoc, executives use Tableau on Redshift, data scientists use Jupyter + Spark. Druid handles sub-second OLAP, Trino handles everything else. Query result cache (Redis) prevents repeat full scans.",
    role: [
      "Ad-hoc SQL on S3 Iceberg — Iceberg metadata pruning skips irrelevant partitions automatically",
      "Federated queries: JOIN playback_sessions (S3) × catalog (Aurora) × user_features (Cassandra) in one SQL",
      "Time-travel queries: SELECT ... FOR SYSTEM_TIME AS OF '...' — A/B test reproducibility",
      "Workload isolation: separate Trino clusters per persona (interactive / BI / data science / backfill)",
      "Query guardrails: max scan = 50TB, query timeout = 10min, per-user memory limit = 32GB",
      "OpenSearch connector: full-text search + structured filters in a single query",
    ],
    tables: [
      {
        name: "analyst_query_patterns",
        columns: [
          { col: "title_completion_funnel",      type: "query pattern", note: "GROUP BY completion_decile — where do users drop off?" },
          { col: "ab_test_attribution",          type: "query pattern", note: "JOIN fact_plays + ab_assignments → lift per variant" },
          { col: "churn_precursor_signals",      type: "query pattern", note: "users who cancelled 30d later — what did they watch last?" },
          { col: "device_quality_correlation",   type: "query pattern", note: "buffer_ratio × device_type — is Smart TV worse than Mobile?" },
          { col: "search_to_play_funnel",        type: "query pattern", note: "search_query → impression → click → play conversion rate" },
          { col: "encoding_bitrate_efficiency",  type: "query pattern", note: "per-title actual vs target bitrate vs VMAF score" },
          { col: "gdpr_impact_analysis",         type: "query pattern", note: "how many rows contain user X across all tables?" },
        ],
        notes: "Trino federation: Iceberg (main lake) + Aurora (catalog/billing) + Cassandra (user history) + OpenSearch (search logs) in a single JOIN.",
      },
      {
        name: "query_engine_matrix",
        columns: [
          { col: "Business Analyst",   type: "Tableau + Druid",       note: "< 1s — pre-aggregated rollups" },
          { col: "Data Analyst",       type: "Trino SQL",             note: "< 60s — Iceberg partition pruning" },
          { col: "Data Scientist",     type: "Jupyter + Spark EMR",   note: "minutes — full dataset exploration" },
          { col: "Engineer",           type: "Trino CLI / SDK",       note: "< 30s — operational queries" },
          { col: "Finance / Exec",     type: "Tableau + Redshift",    note: "< 3s — curated DW tables" },
        ],
      },
    ],
    tools: [
      "Trino (Netflix open-sourced Presto)",
      "AWS Athena (serverless, lightweight queries)",
      "Apache Druid (sub-second OLAP rollups)",
      "AWS Redshift Serverless (structured BI)",
      "Tableau (executive + product dashboards)",
      "Jupyter + Spark (data science exploration)",
      "Apache Superset (self-serve visualisation)",
      "Redis (query result cache — 1h TTL)",
    ],
    dataFlows: [
      { direction: "in",  from_to: "← S3 Iceberg (Silver, Gold, Feature)", format: "Parquet",   freq: "on query" },
      { direction: "in",  from_to: "← AWS Glue Catalog (schema)",         format: "metadata",   freq: "on query" },
      { direction: "in",  from_to: "← Aurora / Cassandra (federation)",   format: "JDBC/CQL",   freq: "on query" },
      { direction: "out", from_to: "→ Tableau / Jupyter (results)",       format: "ResultSet",  freq: "on query" },
      { direction: "out", from_to: "→ Redis (result cache)",              format: "serialized", freq: "on query" },
    ],
    sla: "Interactive queries (last 7 days, < 10 partitions) < 10s. Historical scans (90 days) < 5min. Druid dashboards < 1s.",
    notes: "Cluster isolation is critical at Netflix scale: an analyst running a full 90-day scan without guardrails would starve 50 dashboard queries. Separate clusters + resource groups + scan limits.",
  },

  monitoring: {
    title: "Data Quality & Observability", category: "Layer 10 · Cross-cutting", color: "#94a3b8",
    description: "Wrong data is worse than no data — silent corruption leads to bad product decisions and compliance violations. Netflix uses a defence-in-depth quality model: schema enforcement at ingest, statistical anomaly detection via Flink, table-level checks via Amazon Deequ/Great Expectations, dbt tests on every DW model, and OpenLineage-based lineage tracking in DataHub. GDPR deletion cascades are triggered via Airflow using the lineage graph.",
    role: [
      "Schema Registry: rejects incompatible Avro changes at produce time — prevents schema drift silently",
      "Flink anomaly detector: event volume drop > 30% in 5-min window → PagerDuty P1",
      "Deequ / Great Expectations: null rate, cardinality, value range, referential integrity — per Iceberg write",
      "Volume reconciliation: compare Kafka offset count vs Iceberg row count for each hourly partition",
      "dbt tests: not_null, unique, accepted_values, relationships — block table publish on failure",
      "DataHub / OpenLineage: column-level lineage — every Spark + Flink job emits OpenLineage events",
      "GDPR deletion cascade: lineage graph identifies all downstream tables containing user data",
      "Data freshness SLA monitor: alert if Iceberg partition not updated within expected window",
    ],
    tables: [
      {
        name: "data_quality_results (monitoring table)",
        pk: "check_id",
        columns: [
          { col: "check_id",         type: "UUID" },
          { col: "table_name",       type: "STRING",    note: "e.g. silver.playback_session" },
          { col: "check_name",       type: "STRING",    note: "row_count_threshold|null_rate|referential_integrity|volume_anomaly" },
          { col: "run_at",           type: "TIMESTAMP" },
          { col: "status",           type: "ENUM",      note: "PASS|WARN|FAIL" },
          { col: "expected_value",   type: "STRING",    note: "threshold or range" },
          { col: "actual_value",     type: "STRING",    note: "observed value" },
          { col: "row_count",        type: "BIGINT",    note: "table row count at check time" },
          { col: "failure_msg",      type: "TEXT",      note: "null on PASS" },
          { col: "partition_key",    type: "STRING",    note: "which partition was checked" },
        ],
        notes: "FAIL on critical checks (null_rate > 0.1% on PK, row_count < 50% of 7d avg) → table publish blocked → PagerDuty + Slack.",
      },
      {
        name: "gdpr_deletion_workflow",
        columns: [
          { col: "step_1",  type: "action", note: "resolve all tokens/aliases for the subject user_id" },
          { col: "step_2",  type: "action", note: "KMS key deletion = crypto-shredding (instant — PII fields encrypted per-user)" },
          { col: "step_3",  type: "action", note: "Kafka tombstone (null value) for compacted topics" },
          { col: "step_4",  type: "action", note: "Iceberg DELETE + position-delete files on Silver/Gold tables" },
          { col: "step_5",  type: "action", note: "Cassandra DELETE by profile_id (user history, features)" },
          { col: "step_6",  type: "action", note: "Redis key deletion (online feature store)" },
          { col: "step_7",  type: "action", note: "ML model retrain exclusion list — suppress user_id from future training" },
          { col: "step_8",  type: "action", note: "write immutable compliance audit record to S3 audit bucket" },
        ],
        notes: "KMS key deletion = instant. Kafka tombstone propagation = hours. Iceberg DELETE + compaction = up to 7 days. Total well within 30-day GDPR window.",
      },
    ],
    tools: [
      "Amazon Deequ (Scala — Spark-native quality checks)",
      "Great Expectations (Python — notebook-friendly)",
      "Apache Flink (volume anomaly detection)",
      "dbt tests (DW layer — not_null, unique, relationships)",
      "OpenLineage + Marquez (lineage emission from Spark/Flink)",
      "DataHub / Apache Atlas (data catalog + lineage UI)",
      "Grafana + Prometheus (pipeline health dashboards)",
      "PagerDuty (P0/P1 alerts) + Slack (P2/P3)",
    ],
    dataFlows: [
      { direction: "in",  from_to: "← All Iceberg tables (quality checks)", format: "Parquet",  freq: "per Spark job run" },
      { direction: "in",  from_to: "← Kafka (volume anomaly detection)",   format: "metrics",  freq: "real-time" },
      { direction: "in",  from_to: "← Spark/Flink jobs (lineage events)",  format: "OpenLineage JSON", freq: "on job run" },
      { direction: "out", from_to: "→ Grafana (data health dashboard)",    format: "metrics",  freq: "real-time" },
      { direction: "out", from_to: "→ PagerDuty (P0/P1 failures)",        format: "webhook",  freq: "on failure" },
      { direction: "out", from_to: "→ DataHub (lineage + catalog updates)",format: "REST API", freq: "on job run" },
    ],
    sla: "Quality checks run after every Spark write. FAIL blocks table publish within 5min. GDPR deletion complete within 30 days (regulatory requirement).",
    notes: "Lineage-based impact analysis: 'which ML models, dashboards, and downstream tables depend on silver.playback_session?' — answered in < 2s via DataHub. Critical for schema change impact assessment.",
  },

};

export type InterviewQA = { q: string; difficulty: "easy" | "medium" | "hard"; a: string };

export const PIPELINE_INTERVIEW_QA: Record<string, InterviewQA[]> = {
  clickstream: [
    { difficulty: "medium", q: "How does the Netflix client SDK guarantee no P0/P1 event loss even with flaky connectivity?",
      a: "The SDK writes P0/P1 events to a local SQLite ring-buffer before attempting network delivery. It uses exponential backoff with jitter (2^n * rand, capped at 2h) to retry. The SDK only drops an event from SQLite once it receives an ack from the gateway (HTTP 200 with the Kafka offset). P4/P3 events are never persisted — they are simply not retried if the network fails." },
    { difficulty: "hard", q: "Why use UUID v7 (time-ordered) as the event_id rather than UUID v4 (random)?",
      a: "UUID v7 embeds a millisecond timestamp in the first 48 bits, making them lexicographically sortable. This matters for two reasons: (1) Kafka partition assignment — the gateway can extract time from the ID without parsing the full event, useful for time-based routing. (2) Bloom filter efficiency — time-ordered UUIDs have better cache locality for dedup checks. UUID v4 is fully random, which causes cache misses in Bloom filters at high throughput." },
    { difficulty: "easy", q: "What is the tradeoff between batching more events vs fewer at the SDK level?",
      a: "Larger batches = better compression ratio and fewer HTTP round trips (less overhead). But they increase buffering latency — a 500-event batch at 10 events/sec takes 50 seconds before flushing. For P0 events (payment), Netflix flushes immediately (batch size = 1). For P3/P4, it waits for 50 events or 30 seconds. The batch threshold is dynamic: on poor connectivity, the SDK accumulates more to maximise the chance of a single successful delivery." },
  ],
  kafka_ingest: [
    { difficulty: "hard", q: "Your Kafka consumer lag is growing. Walk through your diagnosis and fix.",
      a: "Step 1: kafka-consumer-groups.sh --describe to see lag per partition. Is it one partition (hot key/skew) or all (underprovisioned consumer)? Step 2: If all partitions — check consumer CPU, GC pauses, slow downstream writes. If one partition — check partition key distribution (e.g. title_id for a viral show). Fix for hot partition: change key to a higher-cardinality field or salt (append rand(100) to key). Fix for all: scale consumer group (limited by partition count). Long-term: increase partition count, but warn that this breaks ordering guarantees for keyed consumers." },
    { difficulty: "hard", q: "How do you achieve exactly-once semantics from the SDK all the way to S3?",
      a: "Layered approach: (1) SDK assigns UUID event_id at creation — idempotency key. (2) Gateway Bloom-filter deduplicates on event_id in a 30-min sliding window. (3) Kafka producer: enable.idempotence=true + acks=all — broker deduplicates by producerId+sequenceNum. (4) Flink: 2-phase commit via KafkaSink with EXACTLY_ONCE semantic — checkpoints Kafka offsets atomically with sink writes. (5) Iceberg: ACID commits — each Spark job overwrites a partition idempotently. Key insight: you never truly block duplicates at every hop — you make every hop idempotent so duplicates are harmless." },
    { difficulty: "medium", q: "Why is title_id a bad Kafka partition key for playback events?",
      a: "Hot partition risk. When a viral show launches (e.g. a new season of Stranger Things), all playback events for that title_id flood to a single partition. One broker handles all the traffic while others are idle — latency spikes and consumer lag grows on just that partition. Better key: playback_id or profile_id, which are uniformly distributed across users. The tradeoff: you lose ordering guarantees per-title, but playback events are naturally session-scoped so per-title ordering is rarely needed." },
  ],
  flink: [
    { difficulty: "hard", q: "Explain Flink's exactly-once semantics via 2-phase commit. What happens if a task manager crashes mid-checkpoint?",
      a: "Flink uses a distributed snapshot protocol (Chandy-Lamport). The Job Manager injects checkpoint barriers into each source partition. When a Task Manager receives barriers from all inputs, it snapshots its state to S3 (RocksDB incremental snapshot) and pre-commits to sinks (Kafka). The Job Manager only marks the checkpoint complete when ALL task managers confirm. If a task manager crashes before confirming, the checkpoint is aborted — the previous completed checkpoint is used for recovery. The pre-committed Kafka transactions are rolled back. Exactly-once is guaranteed because the checkpoint and the Kafka commit happen atomically." },
    { difficulty: "medium", q: "You have a Flink session window job. Mobile events can arrive 4 hours late (user was on a plane). How do you handle this?",
      a: "A 4-hour allowed lateness on session windows would keep state for 4 hours per user — 15M users × 4h of state is prohibitively expensive. Instead: set allowed lateness to 5 minutes (covers 99% of late events). For the 1% of very late events (airplane mode), route them via sideOutputLateData to a late-events Kafka topic. A nightly Spark batch job reads this topic and issues Iceberg MERGE INTO corrections on the Silver session table. The real-time count is approximate (+/- 1%); the next morning's batch count is exact. This is the Lambda pattern." },
    { difficulty: "easy", q: "What is the difference between event time and processing time? When would you use each?",
      a: "Event time: when the event happened on the device (embedded in the payload). Processing time: when it arrives at Flink. For business logic (how many plays between 8-9pm?), always use event time — processing time gives wrong answers for late events. For operational SLA monitoring (how fresh is our pipeline?), use processing time — you want to know when data actually arrived. Flink requires watermarks to use event time: watermark = max_event_time_seen - allowed_lateness_duration." },
  ],
  s3_lake: [
    { difficulty: "hard", q: "Compare Apache Iceberg, Hudi, and Delta Lake. Which would you choose and why?",
      a: "All three add ACID + time-travel + schema evolution on top of S3/Parquet. Iceberg: best multi-engine support (Spark, Flink, Trino, Athena all read native Iceberg without any plugin). Hidden partitioning eliminates partition-pruning bugs. Partition evolution changes partitioning live without rewriting data. Chosen by Netflix, Apple, LinkedIn. Hudi: best for high-frequency CDC upserts (merge-on-read is native — Uber invented it for ride events with frequent corrections). Delta Lake: best Databricks integration, weakest portability. Decision: multi-cloud, multi-engine, open standard → Iceberg. High-frequency upserts/CDC → Hudi. Databricks-only shop → Delta." },
    { difficulty: "medium", q: "What is Iceberg's hidden partitioning and why does it matter?",
      a: "In Hive, users write WHERE dt='2024-01-01' to trigger partition pruning — if they forget or format differs, a full table scan happens silently. Iceberg partitioning is defined at the table level using transforms (days(event_timestamp), bucket(256, profile_id)). Query engines just write WHERE event_timestamp BETWEEN ... — Iceberg's planner automatically rewrites to partition predicates using its metadata. You can also change the partition spec (e.g. days → hours) without rewriting existing data — Iceberg tracks which snapshot used which partition spec. This eliminates an entire class of accidental full-table scans." },
    { difficulty: "medium", q: "Why run compaction on an Iceberg table? What happens without it?",
      a: "Kafka Connect writes small Parquet files (one per 5-minute micro-batch per partition = thousands of files/hour). Without compaction: S3 LIST operations become expensive (and slow), Trino query planning reads thousands of file metadata entries, and Parquet column statistics are useless below a certain file size. Compaction merges N small files into M large files (target 512MB) via Spark's rewriteDataFiles action. After compaction: 90% fewer S3 API calls, 5-10x faster query planning, better column-level min/max stats for predicate pushdown." },
  ],
  airflow: [
    { difficulty: "medium", q: "How does a KafkaSensor in Airflow prevent reading incomplete hourly Iceberg partitions?",
      a: "The sensor polls the Kafka consumer group offset for the hourly partition topic. It waits until consumer lag < threshold (e.g. < 1000 events) — meaning Kafka Connect has written all events for that hour to S3. Without this, a Spark job that starts at 14:02 to process the 13:00-14:00 partition might miss events still in-flight in Kafka. The sensor also checks the Iceberg snapshot metadata — a committed snapshot means the write is atomic and complete. Only after both checks pass does the downstream Spark task start." },
    { difficulty: "hard", q: "How do you safely backfill 90 days of a broken pipeline without impacting production?",
      a: "Isolation: run backfill in a separate Airflow pool with lower priority (weight=1 vs production weight=10). Separate EMR cluster or EMR on EKS namespace with resource quotas. Rate-limit S3 writes to avoid throttling production reads. Mark each backfill run with backfill=true in metadata. Incremental: store input_snapshot_id and output_snapshot_id per run — a failed run can restart exactly where it left off without reprocessing. Approval gate: backfill jobs that touch Gold or Feature tables require manual approval before writing to production schema — prevents broken data from reaching ML training. Reconcile: after backfill, compare row counts against Kafka replay counts for the same time range." },
  ],
  spark: [
    { difficulty: "medium", q: "How do you prevent data skew in Spark at petabyte scale?",
      a: "Detection: Spark UI Stage details — if max task duration = 10× median, you have skew. Fix 1: Enable AQE (spark.sql.adaptive.enabled=true) — Spark 3 auto-detects hot partitions at runtime and splits them. Fixes ~80% of cases. Fix 2: Salting — append rand(100) to the join key on the left side, replicate right side 100×, then reaggregate to remove salt. Fix 3: Broadcast join — if one side is < 10GB, broadcast it to all executors (no shuffle). Fix 4: Handle null keys separately — anonymous user_ids are often the hot key; process them in a separate job." },
    { difficulty: "hard", q: "Explain SCD Type 2 in the context of the Netflix data warehouse. Why does it matter for revenue attribution?",
      a: "Slowly Changing Dimension Type 2: instead of updating a user's record when their plan changes, insert a new row with effective_from and effective_to dates. The old row's effective_to is set to today; the new row's effective_to is null (current). When you join fact_plays to dim_users on user_sk (not user_id), you get the plan the user was on at the time of each play — not their current plan. This is critical for revenue attribution: if a user watched 100 hours on Premium then downgraded to Basic, you want to attribute those 100 hours to Premium revenue, not Basic." },
    { difficulty: "easy", q: "Why use Spot instances for 70% of EMR task nodes? What's the risk and how is it mitigated?",
      a: "Spot instances cost 70-90% less than On-Demand for the same hardware. The risk: AWS can reclaim a Spot instance with a 2-minute warning. Mitigation: Spark's task-level fault tolerance — when a task node is reclaimed, its in-progress tasks are re-scheduled on other nodes using the last checkpoint. Core nodes (persistent) are On-Demand — they hold HDFS data. Task nodes (ephemeral) only run Spark executors — no data loss when they disappear. Use EMR Instance Fleets with multiple instance types (r5.4xlarge, r5a.4xlarge, m5.8xlarge) to reduce spot interruption risk by not competing for a single type." },
  ],
  druid: [
    { difficulty: "hard", q: "When would you use Druid vs Trino vs Spark for analytics? Give concrete Netflix examples.",
      a: "Druid: sub-second OLAP on pre-aggregated rollups. Best for: live A/B test dashboards (rebuffer rate per experiment variant, refreshed every 30s), ops playback quality monitoring (QoE by region/device). Data is pre-aggregated at ingest — can't do arbitrary JOINs. Trino: ad-hoc SQL on raw Iceberg tables, no pre-aggregation needed. Best for: analyst queries ('what were the top 50 titles by completion rate in France last week?'), federated queries joining S3 + Aurora + Cassandra. Latency: seconds to minutes. Spark: batch, full dataset, complex multi-stage logic. Best for: 90-day ML feature computation, SCD Type 2 joins, retraining datasets. Latency: minutes to hours." },
    { difficulty: "medium", q: "Explain Druid's rollup. How does it compress 700B events/day to 14B rows?",
      a: "At ingest time, Druid groups events by (1-minute time bucket + all dimension columns) and aggregates metrics. For playback events: GROUP BY (minute, region, country, device_type, title_id, experiment_variant), SUM(play_count), SUM(rebuffer_ms), SUM(watch_ms). A minute with 50,000 plays in the US on Smart TV for title X becomes ONE row — 50,000 → 1 (50,000:1 compression for that group). The 700B raw events across all groups compress to ~14B rollup rows. The tradeoff: you lose individual event granularity — you can't ask 'what did user 12345 watch?' from Druid. For that you need Trino on the raw Iceberg table." },
  ],
  feature_store: [
    { difficulty: "hard", q: "How does Feast prevent training-serving skew?",
      a: "Training-serving skew = features computed differently at training time vs serving time. Feast's solution: single Python feature definition drives both paths. Point-in-time correct joins: for each training label (user X, label at timestamp T), Feast fetches only features with feature_time ≤ T — no future data leakage. The same Feast SDK call that generates training data is used at serving time — same code path, same transformations. Feature versioning: every model training job logs the exact feature snapshot ID used. If you retrain, you can reproduce the exact feature set. The offline store (S3 Iceberg) and online store (Redis/DynamoDB) are populated by the same feature pipeline (Spark batch + Flink real-time), eliminating divergence." },
    { difficulty: "medium", q: "Why use Redis for some features and DynamoDB for others in the online feature store?",
      a: "Redis: < 1ms P99, ideal for hot scalar features accessed on every recommendation request (recent_titles_5, current_genre, session_depth). Data is small (< 1KB per user), fits in memory. TTL = 6h to prevent stale data. DynamoDB: < 5ms P99, ideal for larger feature vectors that don't need sub-millisecond access (256-dim ALS embeddings, genre_affinity map). DynamoDB scales to any size without capacity planning; Redis requires careful memory sizing. Cassandra is used for viewing history (wide rows, time-series access pattern). The serving layer makes one call to Redis for context features + one call to DynamoDB for embeddings, then ranks candidates." },
  ],
  rec_model: [
    { difficulty: "hard", q: "How would you design the recommendation pipeline's data flow end-to-end?",
      a: "Feature pipeline (near real-time): Flink reads Kafka playback events → computes user context features (last 5 titles, current genre, session depth) → writes to Feast online store (Redis), TTL 6h. Batch features (nightly): Spark reads 90 days of Silver Iceberg → computes long-horizon features (ALS 256-dim embeddings, genre affinity, churn risk) → writes to Feast offline (S3) + online (DynamoDB). Model training: SageMaker Training Job fetches point-in-time correct features from Feast offline + labels (did user watch > 70% of title?) → trains two-tower NN daily. Batch scoring: top-500 recs per profile written to Cassandra by 05:00 UTC. Serving: homepage reads Cassandra (< 5ms) + optional online re-ranking via SageMaker endpoint for context. New model: shadow deploy → 1% → 5% → 20% → 100% canary with NDCG@10 regression guard." },
    { difficulty: "hard", q: "How does Netflix handle the cold start problem for new users?",
      a: "New users have no history → can't compute personal embeddings → model has no signal. Strategies: (1) Onboarding quiz — ask user to rate 3-5 titles or select genres. Map selections to an initial embedding via a content-based model. (2) Device + location signals — country, device type, time of day → regional popularity bucket as initial recs. No history needed. (3) Exploration strategy — first 5 sessions use high-diversity recs (explore mode). After 10+ plays, shift to exploit mode (personalised). (4) Transfer learning — the model trained on all users implicitly encodes 'users like you in your first week' as a latent factor. Cold users get nearest-neighbour in embedding space from users with similar onboarding signals. (5) A/B test onboarding flows — measure week-2 retention as the north-star metric." },
    { difficulty: "medium", q: "What is NDCG@10 and why is it used to evaluate recommendation quality?",
      a: "NDCG = Normalized Discounted Cumulative Gain. It measures ranking quality where positions matter: a relevant item at rank 1 is worth more than the same item at rank 5 (logarithmic discount). @10 means we only evaluate the top 10 recommendations (the homepage row). NDCG@10 = (sum of relevance_i / log2(i+1)) / ideal_DCG. A drop of > 2% in NDCG@10 vs the champion model triggers automatic rollback. It captures both precision (are the items relevant?) and ranking quality (are the best items at the top?). Alternative: hit rate @10 (binary — did user watch any of the top 10?) is simpler but misses ranking quality." },
  ],
  data_warehouse: [
    { difficulty: "hard", q: "Walk through how you'd design the data warehouse star schema for Netflix analytics.",
      a: "Centre: fact_plays (one row per play, ~2B rows/day). Foreign keys to: dim_users (SCD Type 2 — captures plan at time of watch), dim_titles (title metadata, genre, content_type), dim_dates (calendar, fiscal week, holiday flag). Grain: one row per playback session. Denormalise frequently-joined attributes (country, device_type, genre) directly into fact table to avoid expensive joins at query time. Aggregate tables: title_engagement_daily (one row per title per day — pre-computed completion_rate, avg_rebuffer, play_count) for Tableau dashboards that don't need session-level granularity. dbt manages the lineage: stg_playback_events → int_sessions → fact_plays. dbt tests block table publication: not_null on all FKs, unique on play_id, referential integrity on user_sk." },
  ],
  presto: [
    { difficulty: "hard", q: "How does Trino federate a query across S3 Iceberg, Aurora MySQL, and Cassandra in a single SQL?",
      a: "Trino has pluggable connectors for each data source. Each connector translates Trino's internal plan into the native query for that source (SQL for Aurora, CQL for Cassandra, S3 API + Parquet reads for Iceberg). The Trino coordinator pushes down predicates to each connector — only the relevant data is fetched. For a JOIN across sources, Trino runs the smaller side as a broadcast join (sends the full result of the Aurora query to every worker) and streams the larger side (S3 Iceberg) through. Limitation: cross-source aggregations are computed in Trino's workers — no pushdown. For a 10B-row Iceberg table joined to a 1M-row Aurora table, Trino broadcasts Aurora → 1M rows replicated to all workers → streamed JOIN against Iceberg partitions." },
    { difficulty: "medium", q: "Why do you need separate Trino clusters for interactive vs batch workloads?",
      a: "Without isolation, a data scientist running a 90-day full-scan query (reads 50TB, takes 20 minutes) starves 50 concurrent dashboard queries that each need < 10 seconds. Trino resource groups (like a queue per cluster) help but don't fully isolate. Separate clusters: interactive cluster (8-16 workers, queries time out at 5 min, max scan 10TB) for analysts. Batch cluster (50+ workers, no timeout, no scan limit) for data science. BI cluster (pre-warmed, result cache enabled, queries only against Gold/Redshift tables) for Tableau. The result cache (Redis, 1h TTL) on the BI cluster means a popular Tableau dashboard doesn't re-scan Iceberg on every 30-minute refresh." },
  ],
  monitoring: [
    { difficulty: "hard", q: "How does Netflix implement GDPR right-to-erasure across the entire data pipeline?",
      a: "Challenge: user data exists in Kafka, S3 Parquet, Cassandra, Redis, DynamoDB, and ML model weights. Strategy 1 (primary): Crypto-shredding — every PII field encrypted with a per-user KMS key. To erase a user, delete their KMS key. All encrypted data is instantly unreadable without touching files. Strategy 2: Kafka tombstones — publish null-value record for userId on compacted topics. Log compaction eventually removes the user's data. Strategy 3: Iceberg DELETE — issue DELETE FROM table WHERE user_id = X via Spark. Iceberg tracks as position-delete file; full deletion on next compaction. Strategy 4: Lineage cascade — DataHub lineage graph identifies all downstream tables containing the user. Airflow DAG triggers cascade deletes. ML models: user excluded from next training run. Timeline: KMS deletion = instant; Kafka tombstone = hours; Iceberg compaction = up to 7 days. Total: well within 30-day GDPR window." },
    { difficulty: "medium", q: "How do you monitor data quality at Netflix scale? What are the four dimensions?",
      a: "Four dimensions: (1) Completeness — Great Expectations checks null rates, cardinality. Volume anomaly: expected row count ± 20% of 7-day rolling average → P1 alert. (2) Accuracy — value range checks, referential integrity (all user_sk in fact_plays exists in dim_users), business rule checks (rebuffer_ratio between 0 and 1). (3) Timeliness — freshness SLA per table: Silver < 15min lag, Gold available by 07:00 UTC. Monitoring job checks max(event_time) every 5 minutes. (4) Consistency — daily reconciliation: count(events in Kafka offset range) == count(rows in Iceberg) for same time window. Discrepancy > 0.01% → PagerDuty. Failed quality checks block table publication — downstream ML training never sees corrupt data." },
    { difficulty: "medium", q: "What is OpenLineage and how does it enable impact analysis?",
      a: "OpenLineage is an open specification for capturing data lineage as jobs run. Every Spark and Flink job emits START and COMPLETE events with inputs (which Iceberg tables/partitions were read) and outputs (which tables were written). These events are ingested by DataHub (Netflix's data catalog). Result: a column-level lineage graph where you can ask 'which ML models, dashboards, and downstream Gold tables depend on silver.playback_session?' in < 2 seconds. Use cases: schema change impact analysis (if I add a required column here, what breaks?), GDPR lineage cascade (find all tables containing user X), incident blast radius (if this table has corrupt data for 2 hours, which downstream jobs ingested it?)." },
  ],
};

export type PSDNode = { id: string; label: string; sub: string; icon: string; x: number; y: number; color: string };
export type PSDEdge = { from: string; to: string; color: string; dur?: number; label?: string };

export const PIPELINE_VW = 1900, PIPELINE_VH = 780;

export const PIPELINE_NODES: PSDNode[] = [
  { id: "clickstream",    label: "Event SDK",         sub: "700B events/day",   icon: "📡", x: 100,  y: 200, color: "#e50914" },
  { id: "kafka_ingest",   label: "Kafka + Gateway",   sub: "8 PB/day",          icon: "⚡", x: 320,  y: 200, color: "#f59e0b" },
  { id: "flink",          label: "Flink Streaming",   sub: "< 500ms · EOS",     icon: "🌊", x: 570,  y: 100, color: "#ef4444" },
  { id: "s3_lake",        label: "S3 + Iceberg",      sub: "60 PB · Medallion", icon: "🗄️",  x: 570,  y: 300, color: "#3b82f6" },
  { id: "airflow",        label: "Airflow / Maestro", sub: "800+ DAGs",         icon: "🌬️", x: 570,  y: 530, color: "#84cc16" },
  { id: "spark",          label: "Spark on EMR",      sub: "Batch · ALS · SCD", icon: "🔥", x: 820,  y: 300, color: "#f97316" },
  { id: "druid",          label: "Apache Druid",      sub: "OLAP · sub-second", icon: "📊", x: 820,  y: 100, color: "#f43f5e" },
  { id: "feature_store",  label: "Feature Store",     sub: "50K features",      icon: "🧮", x: 1070, y: 180, color: "#a855f7" },
  { id: "rec_model",      label: "Rec Model Train",   sub: "ALS + Two-Tower",   icon: "🤖", x: 1070, y: 400, color: "#ec4899" },
  { id: "data_warehouse", label: "Data Warehouse",    sub: "dbt · Star schema", icon: "🏛️",  x: 1070, y: 610, color: "#8b5cf6" },
  { id: "presto",         label: "Trino + Druid",     sub: "10K analysts",      icon: "🔍", x: 1320, y: 380, color: "#14b8a6" },
  { id: "monitoring",     label: "Data Quality",      sub: "Deequ · Lineage",   icon: "🛡️",  x: 1320, y: 620, color: "#94a3b8" },
];

export const PIPELINE_EDGES: PSDEdge[] = [
  { from: "clickstream",   to: "kafka_ingest",   color: "#e50914",  dur: 1.2 },
  { from: "kafka_ingest",  to: "flink",          color: "#ef4444",  dur: 1.4 },
  { from: "kafka_ingest",  to: "s3_lake",        color: "#3b82f6",  dur: 1.8 },
  { from: "kafka_ingest",  to: "druid",          color: "#f43f5e",  dur: 1.6 },
  { from: "flink",         to: "druid",          color: "#f43f5e",  dur: 1.5 },
  { from: "flink",         to: "s3_lake",        color: "#3b82f6",  dur: 2.0 },
  { from: "s3_lake",       to: "spark",          color: "#f97316",  dur: 2.0 },
  { from: "s3_lake",       to: "presto",         color: "#14b8a6",  dur: 2.2 },
  { from: "airflow",       to: "spark",          color: "#84cc16",  dur: 2.5 },
  { from: "spark",         to: "feature_store",  color: "#a855f7",  dur: 1.8 },
  { from: "spark",         to: "data_warehouse", color: "#8b5cf6",  dur: 2.0 },
  { from: "flink",         to: "feature_store",  color: "#a855f7",  dur: 2.2 },
  { from: "feature_store", to: "rec_model",      color: "#ec4899",  dur: 1.6 },
  { from: "s3_lake",       to: "rec_model",      color: "#ec4899",  dur: 2.4 },
  { from: "data_warehouse",to: "presto",         color: "#14b8a6",  dur: 2.0 },
  { from: "data_warehouse",to: "monitoring",     color: "#94a3b8",  dur: 2.8 },
  { from: "s3_lake",       to: "monitoring",     color: "#94a3b8",  dur: 3.0 },
  { from: "kafka_ingest",  to: "monitoring",     color: "#94a3b8",  dur: 3.2 },
];

export const PIPELINE_LAYER_LABELS = [
  { x: 100,  label: "Sources" },
  { x: 320,  label: "Ingest" },
  { x: 570,  label: "Processing" },
  { x: 820,  label: "Serving / Batch" },
  { x: 1070, label: "ML / DW" },
  { x: 1320, label: "Consume / Observe" },
];
